### ISSUE TITLE
拼音的分词是否也要实现按词库分词

### ISSUE THREAD

**Issue by 13428282016** [medcl/elasticsearch-analysis-pinyin#102]
例如：woaizhongguo 分词为 wo ai zhongguo 而不是 wo ai zhong guo

**Comment by medcl** [comment]
你这个需求要先用中文分词，再用 pinyin 做filter

**Comment by 13428282016** [comment]
但是我在客户端输入woshizhongguo得不到wo shi zhongguo。顺便帮我看看高量报错的问题哈。谢谢了
