### ISSUE TITLE
为什么search结果最高分的跟关键词完全不相关

### ISSUE THREAD

**Issue by guoxijun** [medcl/elasticsearch-analysis-pinyin#117]
"mappings" : {
        "users" : {
            "properties" : {
                "realName": {
                    "type": "keyword",
                    "fields": {
                        "pinyin": {
                            "type": "text",
                            "store": "no",
                            "term_vector": "with_offsets",
                            "analyzer": "pinyin_analyzer",
                            "boost": 10
                        }
                    }
                }
        }
     }
我的mapping是这么写的，当_search?q=realName.pinyin:zhou时，分数最高的那个记录，跟zhou这个关键词完全不匹配，是不是mapping写错了？

**Comment by guoxijun** [comment]
测试了一下，发现如果realName是本来是纯字母构成，就会出现这种情况

**Comment by guoxijun** [comment]
分析器解释结果出现大量null
14	
token	"nullnullnullnul"
start_offset	0
end_offset	15
type	"word"
position	14
15	
token	"nullnullnullnull"
start_offset	0
end_offset	16
type	"word"
position	15
16	
token	"nullnullnullnulln"
start_offset	0
end_offset	17
type	"word"
position	16
17	
token	"nullnullnullnullnu"
start_offset	0
end_offset	18
type	"word"
position	17

**Comment by guoxijun** [comment]
额，原来我自己改了分析器代码引起的

**Comment by medcl** [comment]
那这个可以关了么？
