### ISSUE TITLE
安装插件报错

### ISSUE THREAD

**Issue by tianliplus** [medcl/elasticsearch-analysis-pinyin#122]
Downloading file:///home/http_resource/es-5.4.2/downloads/elasticsearch-analysis-ik-5.4.2.zip
[=================================================] 100%
ERROR: `elasticsearch` directory is missing in the plugin zip

**Comment by tianliplus** [comment]
这个插件在新版本的ES上一直装不上，有人知道是怎么回事吗？

**Comment by Torrence** [comment]
直接解压 elasticsearch-analysis-pinyin-{version}.zip 到 your-es-root/plugins/pinyin
