### ISSUE TITLE
keep_none_chinese_together 这个参数并没有用。

### ISSUE THREAD

**Issue by xgj1988** [medcl/elasticsearch-analysis-pinyin#126]
配置如下
`{
  "index": {
    "number_of_replicas": 0,
    "analysis": {
      "analyzer": {
        "jo_analyzer": {
          "type": "custom",
          "tokenizer": "my_pinyin"
        }
      },
      "tokenizer": {
        "my_pinyin": {
          "type": "pinyin",
          "keep_none_chinese": "true",
          "keep_none_chinese_together": "true",
          "keep_joined_full_pinyin": "false",
          "keep_original": "false",
          "remove_duplicated_term": "false",
          "keep_first_letter": "true",
          "keep_separate_first_letter": "false",
          "trim_whitespace": "true",
          "limit_first_letter_length": "16",
          "keep_full_pinyin": "true"
        }
      }
    }
  }
}`

查询如下： http://192.168.1.246:9200/medcl/_analyze?text=DJ音乐家&analyzer=jo_analyzer
DJ音乐家，把DJ拆开了。。可以把text换成任何其他 非中文字符，都有问题。
`{
    "tokens": [
        {
            "token": "d",
            "start_offset": 0,
            "end_offset": 1,
            "type": "word",
            "position": 0
        },
        {
            "token": "djyyj",
            "start_offset": 0,
            "end_offset": 5,
            "type": "word",
            "position": 0
        },
        {
            "token": "j",
            "start_offset": 1,
            "end_offset": 2,
            "type": "word",
            "position": 1
        },
        {
            "token": "yin",
            "start_offset": 2,
            "end_offset": 3,
            "type": "word",
            "position": 2
        },
        {
            "token": "yue",
            "start_offset": 3,
            "end_offset": 4,
            "type": "word",
            "position": 3
        },
        {
            "token": "jia",
            "start_offset": 4,
            "end_offset": 5,
            "type": "word",
            "position": 4
        }
    ]
}`

**Comment by 774630051** [comment]
"none_chinese_pinyin_tokenize": false 加上这个配置就可以了
