### ISSUE TITLE
作者大大 关于es-pinyin 报错的问题 第一次建立分析器没问题 但是下次在用分析器就会报错

### ISSUE THREAD

**Issue by demoCow** [medcl/elasticsearch-analysis-pinyin#130]
![image](https://user-images.githubusercontent.com/13543139/29112486-9c767a32-7d20-11e7-89ed-a898842a6c2d.png)

![image](https://user-images.githubusercontent.com/13543139/29112503-a89a24e4-7d20-11e7-8268-011f20a8ad7b.png)

作者大大已经写好的 analyzer和 tonkeizer filter 都没问题  第一次建立这样的分析器也是没有问题的 但是es关闭后再建立这样的分析器就会报图上的错。。。。求解

**Comment by medcl** [comment]
请问是哪个版本啊？复现的脚本有么？

**Comment by demoCow** [comment]
都是5.4.1版本 今天再次提交的时候 OK了 。。。。。。。。。 我想是不是 类加载器出现的问题
