### ISSUE TITLE
检索结果有误的问题

### ISSUE THREAD

**Issue by caoyujie** [medcl/elasticsearch-analysis-pinyin#14]
实验证明输入任何的内容都会显示所有的的记录，跟关键字无关。请教这是怎么回事?

**Comment by medcl** [comment]
有case吗?发一下/

**Comment by i6448038** [comment]
给的例子，我又加入了一个数据：“name:黄大海”,结果我搜索“hdh”的时候，还是出现“刘德华”
curl http://localhost:9200/medcl/folks/_search?q=name:hdh
{"took":4,"timed_out":false,"_shards":{"total":5,"successful":5,"failed":0},"hits":{"total":1,"max_score":1.4957824,"hits":[{"_index":"medcl","_type":"folks","_id":"andy","_score":1.4957824,"_source":{"name":"刘德华"}}]}}

**Comment by medcl** [comment]
nGram是会匹配上的，不是完整匹配，dh命中的

**Comment by i6448038** [comment]
我按照步骤一步一步写，结果总是结果都匹配不上
![image](https://cloud.githubusercontent.com/assets/6186049/12257803/7869110a-b944-11e5-922d-f338c09783c4.png)
![image](https://cloud.githubusercontent.com/assets/6186049/12257823/a631ad4a-b944-11e5-82be-bd7645340907.png)
![image](https://cloud.githubusercontent.com/assets/6186049/12257840/cdbc7840-b944-11e5-89cd-0d72acbed0e4.png)
![image](https://cloud.githubusercontent.com/assets/6186049/12257857/eef69662-b944-11e5-8675-e047ad14a399.png)

**Comment by medcl** [comment]
你字段都没指定啊，用这个字段：zname.name_pinyin

**Comment by i6448038** [comment]
感谢您的来信！添加什么字段？是添加搜索字段吗？
![image](https://cloud.githubusercontent.com/assets/6186049/12258727/b0ba847e-b94b-11e5-9156-2c6697464e23.png)
![image](https://cloud.githubusercontent.com/assets/6186049/12258754/e789c758-b94b-11e5-839b-e99358dec7ec.png)
但是搜索汉字：“黄大海”就可以
![image](https://cloud.githubusercontent.com/assets/6186049/12258797/47743a04-b94c-11e5-89bb-40dce1993d8e.png)
![image](https://cloud.githubusercontent.com/assets/6186049/12258812/734d9c74-b94c-11e5-92ee-0cac904dd14d.png)

**Comment by i6448038** [comment]
大神，我发现了你插件的一个问题，在查询的时候，如果url中的冒号":"是中文字符，就可以查到数据
![image](https://cloud.githubusercontent.com/assets/6186049/12260584/7c2d861e-b957-11e5-9bce-5cfb3286951f.png)
![image](https://cloud.githubusercontent.com/assets/6186049/12260598/8db3788a-b957-11e5-91d8-73693e5f50de.png)
但是如果冒号是英文字符”:“，就会出现这个问题：
![image](https://cloud.githubusercontent.com/assets/6186049/12260649/c4e3f190-b957-11e5-839c-6fc51152b75d.png)

**Comment by medcl** [comment]
太旧了，关闭了，有问题重新开
