### ISSUE TITLE
官网最新发布6.0版本pinyin 无法使用

### ISSUE THREAD

**Issue by lljstar** [medcl/elasticsearch-analysis-pinyin#143]
创建mapping的时候就出错了，改成true的时候，分词offset又出错
{
    "error": {
        "root_cause": [
            {
                "type": "illegal_argument_exception",
                "reason": "Could not convert [pinyin.store] to boolean"
            }
        ],
        "type": "illegal_argument_exception",
        "reason": "Could not convert [pinyin.store] to boolean",
        "caused_by": {
            "type": "illegal_argument_exception",
            "reason": "Failed to parse value [no] as only [true] or [false] are allowed."
        }
    },
    "status": 400
}

以下为分词的时候 对pinyin处理的错误
{
    "error": {
        "root_cause": [
            {
                "type": "illegal_argument_exception",
                "reason": "startOffset must be non-negative, and endOffset must be >= startOffset, and offsets must not go backwards startOffset=0,endOffset=3,lastStartOffset=2 for field 'name.pinyin'"
            }
        ],
        "type": "illegal_argument_exception",
        "reason": "startOffset must be non-negative, and endOffset must be >= startOffset, and offsets must not go backwards startOffset=0,endOffset=3,lastStartOffset=2 for field 'name.pinyin'"
    },
    "status": 400
}

**Comment by yin-bp** [comment]
I have the problem too when bulk insert and update documents.

`{"index": {"_type": "boosmap","_id": "38130122", "_index": "pboos-map-adress-1503973107"}}
{"cityName": "鹰潭市", "standardAddrId": "38130122", "detailName": "鹰潭市贵溪市花园办事处建设路四冶生活区2-11栋3单元1层101", "location": "28.292781,117.238963", "countyName": "贵溪市"}
{"index": {"_type": "boosmap","_id": "38130122", "_index": "pboos-map-adress-1503973107"}}
{"cityName": "潭市", "standardAddrId": "38130122", "detailName": "鹰潭市贵溪市花园办事处建设路四冶生活区2-11栋3单元1层101", "location": "28.292781,117.238963", "countyName": "贵溪市"}
`

the first insert,the second update the document. 

the mapping is ：
`{
            "template": "pboos-map-adress-*",
            "settings": {
                "number_of_shards": 6,
                "index.refresh_interval": "5s",
                "analysis" : {
                    "analyzer" : {
                        "pinyin_analyzer" : {
                            "tokenizer" : "my_pinyin"
                        }
                    },
                    "tokenizer" : {
                        "my_pinyin" : {
                            "type" : "pinyin",
                            "keep_separate_first_letter" : false,
                            "keep_full_pinyin" : true,
                            "keep_original" : true,
                            "limit_first_letter_length" : 16,
                            "lowercase" : true,
                            "remove_duplicated_term" : true
                        }
                    }
                }
            },
            "mappings": {
                "boosmap": {
                    "properties": {
                        "standardAddrId":{
                            "type":"keyword"
                        },
                        "detailName": {
                            "type": "text",
                            "term_vector": "with_offsets",
                            "analyzer": "pinyin_analyzer",
                            "boost": 10,
                            "fields": {
                                "keyword": {
                                    "type": "keyword"
                                }
                            }
                        },
                        "cityName":{
                            "type": "text",
                            "fields": {
                                "keyword": {
                                    "type": "keyword"
                                }
                            }
                        },
                        "countyName":{
                            "type": "text",
                            "fields": {
                                "keyword": {
                                    "type": "keyword"
                                }
                            }
                        },
                        "location":{
                            "type": "geo_point"
                        }

                    }
                }
            }
        }`

**Comment by mzshow** [comment]
是的，在ES6.0上我也出现了此问题！

**Comment by medcl** [comment]
收到，我看看什么问题

**Comment by medcl** [comment]
可以发我一下完整的复现脚本么、然后确认插件和 es 都是6.0么？
我按下面的流程，没有发现问题上面的异常。
```

PUT _template/pinyin
{
  "template": "pboos-map-adress-*",
  "settings": {
    "number_of_shards": 6,
    "index.refresh_interval": "5s",
    "analysis": {
      "analyzer": {
        "pinyin_analyzer": {
          "tokenizer": "my_pinyin"
        }
      },
      "tokenizer": {
        "my_pinyin": {
          "type": "pinyin",
          "keep_separate_first_letter": false,
          "keep_full_pinyin": true,
          "keep_original": true,
          "limit_first_letter_length": 16,
          "lowercase": true,
          "remove_duplicated_term": true
        }
      }
    }
  },
  "mappings": {
    "boosmap": {
      "properties": {
        "standardAddrId": {
          "type": "keyword"
        },
        "detailName": {
          "type": "text",
          "term_vector": "with_offsets",
          "analyzer": "pinyin_analyzer",
          "boost": 10,
          "fields": {
            "keyword": {
              "type": "keyword"
            }
          }
        },
        "cityName": {
          "type": "text",
          "fields": {
            "keyword": {
              "type": "keyword"
            }
          }
        },
        "countyName": {
          "type": "text",
          "fields": {
            "keyword": {
              "type": "keyword"
            }
          }
        },
        "location": {
          "type": "geo_point"
        }
      }
    }
  }
}
    
GET pboos-map-adress-1/_analyze
{
  "text": ["鹰潭市贵溪市花园办事处建设路四冶生活区2-11栋3单元1层101"],
  "analyzer": "pinyin_analyzer"
}
    
    
POST pboos-map-adress-1/boosmap/1
{
  "cityName": "鹰潭市",
  "standardAddrId": "38130122",
  "detailName": "鹰潭市贵溪市花园办事处建设路四冶生活区2-11栋3单元1层101",
  "location": "28.292781,117.238963",
  "countyName": "贵溪市"
} 
```

**Comment by lljstar** [comment]
嗯，是用的目前官方最新发布的6.0版本，下载的也是你的6.0版本的pinyin插件。官方使用的是RPM包，安装在Centos7上。（这个部署过2次，可以肯定没有问题）。目前使用filter方式可以绕过 "tokenizer"  的错误。

错误重现很简单，直接使用官方6.0rpm包安装es后，再安装6.0 pinyin插件,使用你的git上操作代码就能重现（我已经重新部署2次重现过,filter方式不会出错) ..  创建好_index和mapping_后，连续插入几条记录这个问题才会出现（name:姓名)，有时候插入几条都不会出错，再继续插入新的数据 就会出现startoffset,endoffset的错误.  但继续插入的name姓名只有一个汉字的时候就不会出错。

**Comment by lljstar** [comment]
看官方论坛说明可能是lucece版本引起的，5.6版本没有出错，用的是6.x的luece版本，6.0 es用的是7.X版本

**Comment by medcl** [comment]
恩，看到了，bulk 就会复现。

**Comment by lljstar** [comment]
哈哈，问一下，google上的ik 版本也是你写的吗，2012年的，我很早用solr的时候，就用的这个版本。

**Comment by medcl** [comment]
ik不是我写的，ik 的原作者是林良益，我只是维护这个 es 的插件。原 ik 地址见项目介绍的链接。

**Comment by medcl** [comment]
> IndexWriter, used to add, update and delete documents in your index, will no longer accept broken token offsets sometimes produced by mis-behaving token filters. Offsets are used for highlighting, and broken offsets, where the end offset for a single token comes before the start offset, or the start offset of a token goes backwards versus the previous token, can only break search-time highlighting. So with this change, Lucene prevents such mistakes at index time by throwing an exception. To ease this transition for cases where users didn’t even know their analyzer was producing broken offsets, we’ve also added a few token filters to “correct” offsets before they are passed to
> IndexWriter.

7不支持多种类型的 token 混合在一起的方式，也就是 offset 有交叉的情况，目前的 pinyin 可以通过设置参数，不允许产生交叉token的情况，就可以，也就是后面需要按一种分词情况配置一个 multi-field，一个 analyzer。

**Comment by medcl** [comment]
插件参数我需要重构一下。简化一下配置。再提供几种模式供选择。

**Comment by yin-bp** [comment]
使用的插件和es的版本都是6.0，脚本和完整的数据样例，已经上面已经发出来了，都是类似这样的，采用bulk操作：

```
{"index": {"_type": "boosmap", "_id": "38132426", "_index": "pboos-map-adress-1503973107"}}
{"cityName": "鹰潭市", "standardAddrId": "38132426", "detailName": "鹰潭市贵溪市花园办事处建设路四冶生活区1-2栋1单元2层201", "location": "28.292781,117.238963", "countyName": "贵溪市"}
{"index": {"_type": "boosmap", "_id": "38132424", "_index": "pboos-map-adress-1503973107"}}
{"cityName": "鹰潭市", "standardAddrId": "38132424", "detailName": "鹰潭市贵溪市花园办事处建设路四冶生活区1-2栋1单元1层101", "location": "28.292781,117.238963", "countyName": "贵溪市"}
{"index": {"_type": "boosmap", "_id": "38132421", "_index": "pboos-map-adress-1503973107"}}
{"cityName": "鹰潭市", "standardAddrId": "38132421", "detailName": "鹰潭市贵溪市花园办事处建设路四冶生活区1-3栋4单元2层202", "location": "28.292781,117.238963", "countyName": "贵溪市"}
{"index": {"_type": "boosmap", "_id": "38132420", "_index": "pboos-map-adress-1503973107"}}
{"cityName": "鹰潭市", "standardAddrId": "38132420", "detailName": "鹰潭市贵溪市花园办事处建设路四冶生活区1-3栋1单元3层301", "location": "28.292781,117.238963", "countyName": "贵溪市"}
{"index": {"_type": "boosmap", "_id": "38132414", "_index": "pboos-map-adress-1503973107"}}
{"cityName": "鹰潭市", "standardAddrId": "38132414", "detailName": "鹰潭市贵溪市花园办事处建设路四冶生活区1-3栋1单元1层102", "location": "28.292781,117.238963", "countyName": "贵溪市"}
{"index": {"_type": "boosmap", "_id": "38132413", "_index": "pboos-map-adress-1503973107"}}
```

数据存放在文件中，操作的代码如下：
```
String data = FileUtil.getFileContent("F:\\拼音搜索\\maps\\maps_0","UTF-8");

	    long time = System.currentTimeMillis();
		ClientInterface clientUtil = ElasticSearchHelper.getRestClientUtil();
		String temp = clientUtil.executeHttp("_bulk",data, ClientUtil.HTTP_POST);
		System.out.println(temp);
		System.out.println("耗时："+(System.currentTimeMillis() - time)+"毫秒");
```

**Comment by medcl** [comment]
Mapping修改一下：
```
PUT _template/pinyin
{
  "template": "pboos-map-adress-*",
  "settings": {
    "number_of_shards": 6,
    "index.refresh_interval": "5s",
    "analysis": {
      "analyzer": {
        "pinyin_analyzer": {
          "tokenizer": "my_pinyin"
        }
      },
      "tokenizer": {
        "my_pinyin": {
          "type": "pinyin",
          "keep_separate_first_letter": false,
          "keep_first_letter": false,
          "keep_full_pinyin": true,
          "keep_original": false,
          "limit_first_letter_length": 16,
          "lowercase": true,
          "remove_duplicated_term": true
        }
      }
    }
  },
  "mappings": {
    "boosmap": {
      "properties": {
        "standardAddrId": {
          "type": "keyword"
        },
        "detailName": {
          "type": "text",
          "term_vector": "with_offsets",
          "analyzer": "pinyin_analyzer",
          "boost": 10,
          "fields": {
            "keyword": {
              "type": "keyword"
            }
          }
        },
        "cityName": {
          "type": "text",
          "fields": {
            "keyword": {
              "type": "keyword"
            }
          }
        },
        "countyName": {
          "type": "text",
          "fields": {
            "keyword": {
              "type": "keyword"
            }
          }
        },
        "location": {
          "type": "geo_point"
        }
      }
    }
  }
}
```

**Comment by medcl** [comment]
新的 release 已经上传，新增了参数来控制 offset，默认所有的 offset 不处理的。如果需要用到 offset 相关的请开启参数，然后抱保证没有 overlap 的 token，根据不同的需要配置多个字段。

**Comment by medcl** [comment]
第一个关于 `Could not convert [pinyin.store] to boolean` 的问题是例子没有更新，已 fix
