### ISSUE TITLE
每个汉字的首字母组合、全拼，无法检索。 

### ISSUE THREAD

**Issue by videni** [medcl/elasticsearch-analysis-pinyin#146]
## 出现问题的分析步骤
![image](https://user-images.githubusercontent.com/4058341/33708632-f0cbe0dc-db75-11e7-830e-168b602410b4.png)
这张图表明`武尊`已被转化为全拼，和首字母的组合。

![image](https://user-images.githubusercontent.com/4058341/33708668-065013b0-db76-11e7-941f-9082aee10278.png)
`武尊`的id为1503， 但却没得到任何分析。 表明索引中不存在全拼和首字母的索引。但通过下列方式，却表明存在。

![image](https://user-images.githubusercontent.com/4058341/33711310-899f721c-db7e-11e7-8560-9072763abd13.png)

## 问题
为什么通过match_phrase无法检索到任何记录？

![image](https://user-images.githubusercontent.com/4058341/33711371-b164dbca-db7e-11e7-9ca9-a58065179379.png)

## 配置
```
    "settings": {
      "index": {
        "number_of_shards": "1",
        "provided_name": "idx_tsy_game",
        "creation_date": "1512626487641",
        "analysis": {      
          "analyzer": {
            "pinyin_analyzer": {
              "tokenizer": "tsy_pinyin"
            }
          },
          "tokenizer": {
            "tsy_pinyin": {
              "keep_joined_full_pinyin": "true",
              "lowercase": "true",
              "keep_none_chinese_in_joined_full_pinyin": "true",
              "keep_original": "false",
              "remove_duplicated_term": "true",
              "keep_first_letter": "true",
              "keep_separate_first_letter": "false",
              "type": "pinyin",
              "limit_first_letter_length": "16",
              "keep_full_pinyin": "false"
            }
          }
        },
        "number_of_replicas": "1",
        "uuid": "N-5HOAP-Rt2nVBqgdgPZWQ",
        "version": {
          "created": "6000099"
        }
      }
    }
```
## name属性配置
```
"name": {
            "type": "text",
            "fields": {
              "pinyin": {
                "type": "text",
                "analyzer": "pinyin_analyzer"
              }
          },
```

**Comment by medcl** [comment]
`ignore_pinyin_offset` 默认是开启的，会忽略 term 的位置，而位置和 phrase 查询密切相关。
如果需要支持 phrase 查询，请关闭该参数，同时还必须保证分词的结果不能有位置重复的term，即：可以有 wu和zhun，但不能同时还有 wz，或者只有 wz，但不能有 wu\zhun。
如果需要同时支持两种查询，则建custom 两个 analyzer，分别使用两个子字段，一个是全拼，一个是首字母。主要是term 和位置不能重叠。

**Comment by videni** [comment]
thank, solved ,this can be closed.
