### ISSUE TITLE
如果对中文首字母组合再进行更细粒度的分词

### ISSUE THREAD

**Issue by zl4140035** [medcl/elasticsearch-analysis-pinyin#147]
比如“马三立”，会出现msl，如何再出现m，ms，s，sl这种程度的分词，该如何配置

**Comment by zl4140035** [comment]
还有比如“南中汇丰五九购A”，nzh可以查出来，nzhf就查不出来，

**Comment by medcl** [comment]
首字母得到通过配置 pinyin 分词得到，再通过 ngram 进一步切词。不过分成上面的单字，匹配的准确度会很差。

**Comment by zl4140035** [comment]
这个解决了，自己一开始走进死胡同了，tokenizer用了ngram，然后filter用了pinyin，解决了目前的需求问题，效果也很好
