### ISSUE TITLE
关于pinyin分词正向搜索2

### ISSUE THREAD

**Issue by starckgates** [medcl/elasticsearch-analysis-pinyin#16]
大神，我又来了
刚才正向确实可以，但有个比较实际的问题

http://localhost:9200/tag/_analyze?text=%E5%88%98%E5%BE%B7%E5%8D%8E&analyzer=pinyin_analyzer

后结果是 

{"tokens":[{"token":"ldh liu de hua ","start_offset":0,"end_offset":3,"type":"word","position":1}]}

用prefix搜索 ldh 确实从正向搜出结果的，但是如果搜 liu 这样就没有结果了，这个该怎么办呢？

现在就是想在正向搜索的基础上可以实现 开头字母和pinyin都可以搜出结果。

**Comment by medcl** [comment]
原来es1.4之后,standard filter行为变了,没有把他们按空格切分了,
你把standard换成word_delimiter就行了
es1.7测试通过.

**Comment by starckgates** [comment]
1.6上我做了测试，也是可以的。
主要是有些参数我不知道怎么设置，就比如说word_delimiter，我没找到filter的es内置参数都有什么？这个在哪儿能找到呢？
另外一点，就是如何控制自定义的分词，比如刘德华吧，如果按照刚才的分词方法，可以分成 ldh liu de hua，使用查询的时候使用其中任何一个都能查的到，其实这种分词查询最后也也是根据分词term来查对吧？
不知道您了解百度的查询机制吗？我是一直想做一个公司自己用的“查询建议”，就是在输入pinyin ，开头字母或者中文的时候可以自动完成，比如搜 zg，zhong，zhongguo，中国，都会自动列举出中国的词。现在实现的程度一般，因为总会把无关的词搜出来，比如搜出 中科院，国家图书馆，这些无关的内容。

**Comment by starckgates** [comment]
大神，现在 ik插件和pinyin插件支持1.7吗？我现在这两个都在尝试使用，所以ES版本一直没更新到1.7，还在使用1.6。

**Comment by starckgates** [comment]
还有就是多音字怎么处理呢？比如“长治”，这里读‘chang’，可是分词得出的是‘zhang’，所以，cz有结果，zz无结果。

**Comment by bsc2xp** [comment]
我的需求和 starckgates 一样，但是我只实现了中文的自动提示。想看看能否借助这个插件实现类似百度的拼音提示效果

**Comment by domyway** [comment]
我的需求也一样，如何配置呢

**Comment by medcl** [comment]
新版本已解决多音歧义问题，如有问题可重开本帖
