### ISSUE TITLE
whether can "keep_first_letter"  only enable  in  muti words

### ISSUE THREAD

**Issue by biaotang** [medcl/elasticsearch-analysis-pinyin#181]
我在索引中自定义了一个分词器，采用ik_max_word + pinyin； 索引中插入了多条记录， 索引中有一个字段，字段值如下：
1. 测试文档在这里
2. 测测这个功能
3. 厕所测试
4. 测试文档中有哪些分类
5. 说文档中思创有哪些分类

当我查询 "测试" 或者 "cs" ,  返回结果正常。
但是当我搜索 "侧式"， 分词器把词拆分成  "c ce  s shi";  结果返回第五条记录，这个结果是怎么匹配上的？  medcl大神能详细讲解下吗 ？

 "limit_first_letter_length"  可以设置first letter最大长度， 是不是可以暴露一个参数用来设置最小长度；或者暴露一个参数用来设置区间范围

配置在下面

**Comment by biaotang** [comment]
mine setting as follow:

PUT my_index
{
  "settings": {
    "analysis": {
      "analyzer": {
                "ik_pinyin": {
                    "type": "custom",
                    "tokenizer": "ik_max_word",
                    "filter": ["pinyin"]
                }
            },
            "filter": {
                "pinyin": {
                    "type": "pinyin",
                    "keep_full_pinyin" : false,
                    "keep_none_chinese_in_joined_full_pinyin": true,
                    "none_chinese_pinyin_tokenize": false,
                    "keep_joined_full_pinyin":true
                }
                
            }
    }
  },
  "mappings": {
    "doc": {
      "properties": {
        "name": {
          "type": "text",
          "analyzer": "ik_pinyin"
        }
      }
    }
  }
}

**Comment by medcl** [comment]
用这个 filter 过滤长度为1的就行了
https://www.elastic.co/guide/en/elasticsearch/reference/current/analysis-length-tokenfilter.html
