### ISSUE TITLE
pinyin分词器的多音字

### ISSUE THREAD

**Issue by Gongruixiao** [medcl/elasticsearch-analysis-pinyin#189]
使用了最新版本的6.5.0版本的pinyin分词，针对银行进行解析的时候，还是分成了yinxing
{
    "text":"银行",
    "analyzer":"pinyin_analyzer"
}
{
  "tokens": [
    {
      "token": "yin",
      "start_offset": 0,
      "end_offset": 0,
      "type": "word",
      "position": 0
    },
    {
      "token": "xing",
      "start_offset": 0,
      "end_offset": 0,
      "type": "word",
      "position": 1
    },
    {
      "token": "银行",
      "start_offset": 0,
      "end_offset": 0,
      "type": "word",
      "position": 1
    },
    {
      "token": "yinxing",
      "start_offset": 0,
      "end_offset": 0,
      "type": "word",
      "position": 1
    },
    {
      "token": "yx",
      "start_offset": 0,
      "end_offset": 0,
      "type": "word",
      "position": 1
    }
  ]
}

**Comment by spursy** [comment]
你是如何解决的，我也遇到相同的问题

**Comment by wuyu8995861** [comment]
https://github.com/RickyHuo/elasticsearch-analysis-pinyin
