### ISSUE TITLE
异常startOffset must be non-negative, and endOffset must be >= startOffset

### ISSUE THREAD

**Issue by doubleview** [medcl/elasticsearch-analysis-pinyin#204]
```
PUT global_search_test
{
   "settings": {
      "analysis": {
         "analyzer": {
            "pinyin_analyzer": {
               "tokenizer": "my_pinyin"
            }
         },
         "tokenizer": {
            "my_pinyin": {
               "type": "pinyin",
               "keep_full_pinyin": true,
               "keep_joined_full_pinyin": true,
               "keep_original": true,
               "limit_first_letter_length": 16,
               "lowercase": true,
               "remove_duplicated_term": true,
               "ignore_pinyin_offset": false
            }
         }
      }
   },
   "mappings": {
      "_doc": {
         "_all": {
            "enabled": false
         },
         "properties": {
            "businessId": {
               "type": "keyword"
            },
            "category": {
               "type": "integer"
            },
            "title": {
               "type": "text",
               "term_vector": "with_offsets",
               "analyzer": "pinyin_analyzer",
               "search_analyzer": "pinyin_analyzer"
            }
         }
      }
   }
}

PUT global_search_test/_doc/1
{
    "title":"北京科技大学龙卡"
}


频繁索引数据的话就会报异常

{
   "error": {
      "root_cause": [
         {
            "type": "illegal_argument_exception",
            "reason": "startOffset must be non-negative, and endOffset must be >= startOffset, and offsets must not go backwards startOffset=0,endOffset=8,lastStartOffset=7 for field 'title'"
         }
      ],
      "type": "illegal_argument_exception",
      "reason": "startOffset must be non-negative, and endOffset must be >= startOffset, and offsets must not go backwards startOffset=0,endOffset=8,lastStartOffset=7 for field 'title'"
   },
   "status": 400
}
```

**Comment by fnwib** [comment]
1、打开这个配置  "keep_separate_first_letter" : true 
2、 ’成龙 ‘ 的分词结果：
{
    "tokens": [
        {
            "token": "c",
            "start_offset": 0,
            "end_offset": 1,
            "type": "word",
            "position": 0
        },
        {
            "token": "cheng",
            "start_offset": 0,
            "end_offset": 1,
            "type": "word",
            "position": 0
        },
        {
            "token": "l",
            "start_offset": 3,
            "end_offset": 4,
            "type": "word",
            "position": 1
        },
        {
            "token": "long",
            "start_offset": 3,
            "end_offset": 4,
            "type": "word",
            "position": 1
        },
        {
            "token": "cl",
            "start_offset": 0,
            "end_offset": 2,
            "type": "word",
            "position": 1
        }
    ]
}
3、错误原因是  c和 cheng 的 *_offset 相同

**Comment by doubleview** [comment]
> c

这个配置加上，频繁索引一样会抛异常，并没有效果

**Comment by doubleview** [comment]
这个配置加上没有效果，频繁索引还是会抛异常

**Comment by fnwib** [comment]
我目前的解决办法是，建几个字段。
刘德华
1   full_pinyin -> [liu,de,hua]；
2  first_letter_pinyin -> [l,d,h]
3  han   -> [刘，德，华]

缺点就是不能混合搜。

**Comment by doubleview** [comment]
我目前的解决办法是将ik和pinyin混合, 但注意要把keep_full_pinyin置为false, 是为了避免offset有问题, 也可以防止高亮显示问题
PUT test
{
   "settings": {
      "analysis": {
         "analyzer": {
            "index_pinyin_ik_analyzer": {
               "type": "custom",
               "tokenizer": "ik_max_word",
               "filter": [
                  "index_pinyin_filter"
               ]
            },
            "search_pinyin_ik_analyzer": {
               "type": "custom",
               "tokenizer": "ik_max_word",
               "filter": [
                  "search_pinyin_filter"
               ]
            }
         },
         "filter": {
            "index_pinyin_filter": {
               "type": "pinyin",
               "keep_full_pinyin": false,
               "keep_joined_full_pinyin": true,
               "keep_none_chinese_in_joined_full_pinyin": true,
               "keep_original": true,
               "none_chinese_pinyin_tokenize": false,
               "lowercase": true,
               "remove_duplicated_term": true
            },
            "search_pinyin_filter": {
               "type": "pinyin",
               "keep_first_letter": false,
               "keep_full_pinyin": true,
               "keep_joined_full_pinyin": true,
               "keep_none_chinese_in_joined_full_pinyin": true,
               "keep_original": true,
               "lowercase": true,
               "remove_duplicated_term": true
            }
         }
      }
   }
}

**Comment by medcl** [comment]
开启参数ignore_pinyin_offset呢？

**Comment by doubleview** [comment]
没有效果,都试过了

**Comment by abia321** [comment]
> 开启参数ignore_pinyin_offset呢？

PinyinTokenizer内的reset()方法，应该是同样需要对设置this.processedSortCandidate = false;即可修复这个问题。

https://github.com/medcl/elasticsearch-analysis-pinyin/pull/206

**Comment by medcl** [comment]
fixed with https://github.com/medcl/elasticsearch-analysis-pinyin/commit/c3f9e96c8ff76e044d450e51364f3078735334f4, Thank you @abia321

**Comment by kazaff** [comment]
> 开启参数ignore_pinyin_offset呢？

我将这个参数设置为true后，就ok了~

**Comment by OsmondShine** [comment]
> 开启参数ignore_pinyin_offset呢？
请问开启了之后,pinyin没有位置信息了,用拼音搜索就没法高亮了,这个怎么解决呢
