### ISSUE TITLE
Install Instructions for Elastic Search 2.0

### ISSUE THREAD

**Issue by adallow** [medcl/elasticsearch-analysis-pinyin#22]
Can you provide details about how to compile and package this to install it for Elastic Search 2.0

I would love to use this!

**Comment by medcl** [comment]
git checkout v1.4.0
mvn package
copy zip file from release folder，unzip it into elasticsearch's plugins folder
restart es
have fun.

**Comment by medcl** [comment]
can you check out this repo:
http://github.com/medcl/elasticsearch-rtf

**Comment by adallow** [comment]
BTW Thank you for this, I forgot to write a reply at the time
