### ISSUE TITLE
plugin-descriptor.properties

### ISSUE THREAD

**Issue by c86jeff** [medcl/elasticsearch-analysis-pinyin#23]
ES 2.0 安装需要 plugin-descriptor.properties 文件 并且需要设置好参数
你的master版本中 plugin-descriptor.properties 放在src里了 而且没有配置好参数
你能说明下如何配置参数嘛

**Comment by medcl** [comment]
maven打包之后，在release下面的zip包里面都能找到的

**Comment by c86jeff** [comment]
谢谢解答 非常感谢
