### ISSUE TITLE
plugin-descriptor.properties中'name'参数可能会导致插件无法使用

### ISSUE THREAD

**Issue by atomyliu** [medcl/elasticsearch-analysis-pinyin#24]
今日在测试ES2.1部署新`ik`插件和`pinyin`插件，同时发现了此问题，就是在`plugin-descriptor.properties`文件中，同时用到`name=${elasticsearch.plugin.name}`，在启动ES服务的时候会发现：
``[node-1] loaded [license, marvel-agent, ${elasticsearch.plugin.name}], sites [kopf, sense, head]``
此时在创建索引时用到分词可能会出现索引创建后产生索引异常，分片无法分配的情况；
测试修改为 `name=ik` ,`name=pinyin`后，启动ES服务：
``[node-1] loaded [license, marvel-agent,ik,pinyin], sites [kopf, sense, head]``
再重新创建索引后，问题消失。

**Comment by medcl** [comment]
已fix
