### ISSUE TITLE
按照教程操作，报错Unknown tokenizer type [pinyin] for [my_pinyin]

### ISSUE THREAD

**Issue by yixuan004** [medcl/elasticsearch-analysis-pinyin#248]
{"error":{"root_cause":[{"type":"illegal_argument_exception","reason":"Unknown tokenizer type [pinyin] for [my_pinyin]"}],"type":"illegal_argument_exception","reason":"Unknown tokenizer type [pinyin] for [my_pinyin]"},"status":400}

**Comment by wanghui2333** [comment]
请问怎么解决的？

**Comment by wansho** [comment]
重启 elastic
