### ISSUE TITLE
搜索中拼音粒度太细

### ISSUE THREAD

**Issue by kaelwu** [medcl/elasticsearch-analysis-pinyin#25]
譬如我搜 ceshi(测试等)  他把不属于ceshi的都会搜出来如何改变这个mapping ngram 我用multi_match 添加了operate and这个属性

**Comment by medcl** [comment]
用ngram+ operator=AND是对的，你Ngram的min是多少？再结合一下其他字段，加上权重，比如中文》pingyin非ngram》pinyin ngram

**Comment by kaelwu** [comment]
我知道你的意思了 我现在没设min 我试下你的建议 thanks

**Comment by kaelwu** [comment]
@medcl   我搜huaxi  会匹配出 
![image](https://cloud.githubusercontent.com/assets/8181007/11776551/f59fbb3e-a282-11e5-9074-59a317550a97.png) 这种有办法解决么

**Comment by medcl** [comment]
看你到底是要模糊匹配还是精确匹配了，模糊匹配没有办法，肯定有这样的问题

**Comment by sdpfoue** [comment]
> 用ngram+ operator=AND是对的，你Ngram的min是多少？再结合一下其他字段，加上权重，比如中文》pingyin非ngram》pinyin ngram
请问这个权重如何设置

**Comment by sdpfoue** [comment]
请问『中文》pingyin非ngram》pinyin ngram』这个优先级如何设置

**Comment by medcl** [comment]
太旧了，关闭了，有问题重新开
