### ISSUE TITLE
请问有没有类似pinyin+ik的分词效果呢

### ISSUE THREAD

**Issue by Yani945** [medcl/elasticsearch-analysis-pinyin#27]
大神，pinyin里的"nGram"分词太细了，基本上所有内容都会出来，去掉后只能输入完整的拼音或字符才能出来，请问有没有什么好的解决办法。
这是我按教程的配置:
{
    "index" : {
        "analysis" : {
            "analyzer" : {
                "pinyin_analyzer" : {
                    "tokenizer" : "my_pinyin",
                    "filter" : ["word_delimiter","nGram"]
                }
            },
            "tokenizer" : {
                "my_pinyin" : {
                    "type" : "pinyin",
                    "first_letter" : "prefix",
                    "padding_char" : ""
                }
            }
        }
    }
}

**Comment by chengyuanheng** [comment]
不知道 elasticsearch-analysis-ik-pinyin 这个怎么样 可以研究研究

**Comment by medcl** [comment]
```
{
"index" : {
"analysis" : {
"analyzer" : {
	"ik_pinyin_analyzer" : {
	"type":"custom",
	"tokenizer" : "ik_smart",
	"filter" : ["my_pinyin","word_delimiter"]
}
},
"filter" : {
"my_pinyin" : {
"type" : "pinyin",
"first_letter" : "prefix",
"padding_char" : " "
}
}
}
}
}
```
试试这个

**Comment by chengyuanheng** [comment]
@medcl  大神 我用了你写的 
curl -XPUT http://localhost:9200/medcl/ -d'
{
    "index" : {
        "analysis" : {
            "analyzer" : {
                "custom_pinyin_analyzer" : {
                    "tokenizer" : "ik_smart",
                    "filter" : ["full_pinyin_no_space","full_pinyin_with_space","first_letter_pinyin"]
                }
            },
            "filter" :{
                "full_pinyin_no_space" : {
                    "type" : "pinyin",
                    "first_letter" : "none",
                    "padding_char" : ""
                },
                "full_pinyin_with_space" : {
                    "type" : "pinyin",
                    "first_letter" : "none",
                    "padding_char" : " "

            },
                "first_letter_pinyin" : {
                    "type" : "pinyin",
                    "first_letter" : "only",
                    "padding_char" : ""

            }
        }
        }
    }
}’

结果拼音分词 “音乐家” 分成了
{
  "tokens" : [ {
    "token" : "yinlejia",
    "start_offset" : 0,
    "end_offset" : 3,
    "type" : "CN_WORD",
    "position" : 0
  } ]
}

**Comment by Yani945** [comment]
ok,多谢medcl大神，也谢谢各位热心伙伴,我试试看

**Comment by ln94223** [comment]
ik_smart tokenizer 这个怎么配置大神

**Comment by medcl** [comment]
@chengyuanheng 多音字目前还不支持

**Comment by medcl** [comment]
fixed in master

**Comment by levylll** [comment]
@chengyuanheng 我发现我用这个的时候，只有filter中的第一个配置生效了。。。后面两个似乎都没生效。。。。不知道你有没这个问题。。。

**Comment by medcl** [comment]
setting配置看看，注意括号和拼写
levylll <notifications@github.com>于2016年10月9日 周日下午12:58写道：

**Comment by levylll** [comment]
@medcl 我是在模拟器中给es发送了post请求，想看看这种配置了多个filter的分析器的返回值是什么，模拟器中的返回值只会按照filter中配置的若干个条件中的第一个。
```
{
        "index": {
            "analysis": {
                "analyzer": {
                    "name_analyzer": {
                        "type": "custom",
                        "tokenizer": "ik"
                    },
                    "pinyin_analyzer": {
                        "type": "custom",
                        "tokenizer": "ik",
                        "filter": [
                            "full_pinyin_no_space",
                            "full_pinyin_with_space",
                            "first_letter_pinyin"
                        ]
                    }
                },
                "filter": {
                    "full_pinyin_with_space": {
                        "type": "pinyin",
                        "first_letter": "none",
                        "padding_char": " "
                    },
                    "full_pinyin_no_space": {
                        "type": "pinyin",
                        "first_letter": "none",
                        "padding_char": ""
                    },
                    "first_letter_pinyin": {
                        "type": "pinyin",
                        "first_letter": "only",
                        "padding_char": ""
                    }
                }
            }
        },
        "index.requests.cache.enable": "true"
    }
```

**Comment by medcl** [comment]
filter 使用的是【】

**Comment by levylll** [comment]
analyzer中的filter配置的时候，确实用的是[]，但是在下面配置filter的时候，用[]是会报错，用{}才可以。

**Comment by levylll** [comment]
@medcl 以上。

**Comment by medcl** [comment]
看错了，filter 配置方式是对的，但是不是这么用的，多个 pinyin filter 没有用，第一个 filter 就把中文转成 pinyin 了，后面的自然失效了，如果有多个需求，建议使用 multi-fields，另外新的 pinyin 插件完善了很多，一个 filter 就支持了，配置也不一样了，可以试试看

**Comment by levylll** [comment]
@medcl 哦，是这样子啊，明白你的意思了，真的是多谢了。其实也挺想上新的插件，有在测试环境装过，配置起来确实方便了很多。不过线上的机器更新版本比较麻烦，目前只是有个初步的更新计划。另外很是期待5.0的正式版出来啊，大概什么时候能有正式版本？

**Comment by daorren** [comment]
```
analysis: {
  filter: {
    my_pinyin_filter: {
      type: "pinyin",
      keep_full_pinyin: false,  // true: 刘德华 > [liu, de, hua]
      keep_joined_full_pinyin: true,  // 刘德华 > [liudehua]
      none_chinese_pinyin_tokenize: false,  // true: woshishui > [wo, shi, shui]
      limit_first_letter_length: 16,
      keep_original: true,
      first_letter : "prefix",
      padding_char : " "
    }
  },
  analyzer: {
    my_ik_analyzer: {
      type: "custom",
      char_filter: [ "html_strip" ],
      tokenizer: "ik_smart",
      filter: [ "my_pinyin_filter", "word_delimiter" ],
    }
  }
}
```
@medcl 大神你好，我在使用 `V5.0` ES 和对应的版本插件的时候，上面这样的 analyzer，对 `刘德华` 拿不到想要的 `liudehua` token。

想知道，当前版本该如何构造 pinyin+ik 的效果？

**Comment by zfha** [comment]
@medcl 大神，请问下，我用了你的setting如下
```
PUT test_index
{
  "index" : {
    "analysis" : {
      "analyzer" : {
        "ik_pinyin_analyzer" : {
          "type":"custom",
          "tokenizer" : "ik_smart",
          "filter" : ["my_pinyin","word_delimiter"]
        }
      },
      "filter" : {
        "my_pinyin" : {
          "type" : "pinyin",
          "first_letter" : "prefix",
          "padding_char" : " "
        }
      }
    }
  }
}
``
然后测试分词
```
POST test_index/_analyze
{
  "analyzer": "ik_pinyin_analyzer",
  "text":"道路挖掘"
}
```

出现这个错误，请问下是什么原因
```
{
  "error": {
    "root_cause": [
      {
        "type": "remote_transport_exception",
        "reason": "[pczuo-0][172.17.0.2:9300][indices:admin/analyze[s]]"
      }
    ],
    "type": "null_pointer_exception",
    "reason": null
  },
  "status": 500
}
```

版本号，6.4.0
