### ISSUE TITLE
构建了 8.10.2 ，8.10.3，8.10.4，7.17.14供使用

### ISSUE THREAD

**Issue by lizongbo** [medcl/elasticsearch-analysis-pinyin#295]
elasticsearch-analysis-pinyin 新包构建说明

elasticsearch-analysis-pinyin 作者创业之后应该是没时间维护这个插件了，
没有构建支持8.10.2版本的包，于是自己fork了代码，拉到本地修改修改pom.xml中的版本号，比如：
<elasticsearch.version>8.10.2</elasticsearch.version>
并升级了nlp-lang-1.7.jar 为nlp-lang-1.7.9.jar, nlp-lang组件中拼音数据有更新

修改之后运行构建命令 mvn clean compile package，打包成功，得到elasticsearch-analysis-pinyin-8.10.2.zip
插件安装命令示例：
./elasticsearch-plugin -v install file:///var/services/homes/lizongbo/esplugins/elasticsearch-analysis-pinyin-8.10.2.zip

为方便大家使用，我构建了以下版本的包供使用：

8.10.2,8.10.3,8.10.4,7.17.14

https://github.com/lizongbo/elasticsearch-analysis-pinyin/releases/tag/v8.10.4
https://github.com/lizongbo/elasticsearch-analysis-pinyin/releases/tag/v8.10.3
https://github.com/lizongbo/elasticsearch-analysis-pinyin/releases/tag/v8.10.2
https://github.com/lizongbo/elasticsearch-analysis-pinyin/releases/tag/v7.17.14

有其它版本包需求的也可以在此提出来，我可以构建上传。

**Comment by wanggegedouble** [comment]
可以构建一下 7.17.16 吗

**Comment by medcl** [comment]
https://github.com/infinilabs/analysis-pinyin/releases/tag/v7.17.16

**Comment by wanggegedouble** [comment]
十分感谢。

**Comment by smalon** [comment]
求8.9版本插件

**Comment by medcl** [comment]
https://github.com/infinilabs/analysis-pinyin/releases/tag/v8.9.0

**Comment by yanjinbin** [comment]
xdm  es  8.11.2这个版本 目前  和 https://github.com/infinilabs/analysis-ik 以及这个 都兼容 
不过 安装命令是这个哦 
bin/elasticsearch-plugin install https://github.com/infinilabs/analysis-pinyin/releases/download/v8.11.2/elasticsearch-analysis-pinyin-8.11.2.zip
