### ISSUE TITLE
padding_char是否有bug？

### ISSUE THREAD

**Issue by shadowleing** [medcl/elasticsearch-analysis-pinyin#34]
处理首字母为何要添加分隔符？
例如 “刘德华” => “liu de hua l d h” 为何不是“liu de hua ldh”

> if (this.padding_char.length() > 0) {
                                if (stringBuilder.length() > 0) stringBuilder.append(this.padding_char);
                                if (firstLetters.length() > 0) firstLetters.append(this.padding_char);
                            }

看了代码，firstLetters是否不应该加padding_char？ 或者将stringBuilder 和 firstLetters的分隔符分别设置更合理？

另外是否有考虑对多音字的支持？pinyin4j本身支持多音字...

thx...

**Comment by medcl** [comment]
恩，这个是个bug，多音字会加上
