### ISSUE TITLE
最新版本支持 2.2 么？

### ISSUE THREAD

**Issue by CherryOP** [medcl/elasticsearch-analysis-pinyin#36]
最新版本支持 2.2 么？ 有没有更详细的操作文档？

**Comment by slixurd** [comment]
clone最新版本的仓库，自行compile和package。注意package时可能test fail，加上skip test就可以打包了。
打包后把plugin-descriptor.properties的版本从2.1.1改成2.2.0就行。目前没看到不兼容崩掉的情况

**Comment by medcl** [comment]
already in master
