### ISSUE TITLE
使用最新版elasticsearch-rtf按照 pinyin 插件一步步测试，查询结果不准确的问题

### ISSUE THREAD

**Issue by linux007** [medcl/elasticsearch-analysis-pinyin#37]
hi, @medcl大神，我下载了最新的elasticsearch-rtf，按照pinyin插件一步步执行，最后查询结果不准确，总是无法匹配查询结果，反复重复了几遍，不知问题出现在哪里，希望有时间指教一下，先谢过 :)

**Comment by medcl** [comment]
过程，错误，贴一下

**Comment by linux007** [comment]
执行过程如下：
`curl -XPUT http://localhost:9200/medcl -d'
{
    "index" : {
        "analysis" : {
            "analyzer" : {
                "pinyin_analyzer" : {
                    "tokenizer" : "my_pinyin",
                    "filter" : ["word_delimiter","nGram"]
                }
            },
            "tokenizer" : {
                "my_pinyin" : {
                    "type" : "pinyin",
                    "first_letter" : "prefix",
                    "padding_char" : " "
                }
            }
        }
    }
}'`

创建mapping

`curl -XPOST http://localhost:9200/medcl/folks/_mapping -d'
{
    "folks": {
        "properties": {
            "name": {
                "type": "multi_field",
                "fields": {
                    "name": {
                        "type": "string",
                        "store": "no",
                        "term_vector": "with_positions_offsets",
                        "analyzer": "pinyin_analyzer",
                        "boost": 10
                    },
                    "primitive": {
                        "type": "string",
                        "store": "yes",
                        "analyzer": "keyword"
                    }
                }
            }
        }
    }
}'`

索引

curl -XPOST http://localhost:9200/medcl/folks/andy -d'{"name":"刘德华"}'

测试
curl http://localhost:9200/medcl/folks/_search?pretty&q=name:zhang

执行结果如下：

`[root@05-64 elasticsearch-rtf]#{
  "took" : 12,
  "timed_out" : false,
  "_shards" : {
    "total" : 5,
    "successful" : 5,
    "failed" : 0
  },
  "hits" : {
    "total" : 1,
    "max_score" : 1.0,
    "hits" : [ {
      "_index" : "medcl",
      "_type" : "folks",
      "_id" : "andy",
      "_score" : 1.0,
      "_source" : {
        "name" : "刘德华"
      }
    } ]
  }
}`

在查询过程中没有发现明显错误

**Comment by kinghs** [comment]
zhang里面h和liudehua的h匹配了，所以搜到了？
