### ISSUE TITLE
大神，按照你的配置，做ik+pinyin分词，用拼音搜不出结果

### ISSUE THREAD

**Issue by 651016236** [medcl/elasticsearch-analysis-pinyin#41]
我的配置：
`{
  "settings":{
    "index":{
      "number_of_shards": 5,
      "number_of_replicas": 1,
      "analysis" : {
          "analyzer" : {
              "custom_pinyin_analyzer" : {
                  "tokenizer" : "ik_max_word",
                  "filter" : ["full_pinyin_no_space","full_pinyin_with_space","first_letter_pinyin"]
              }
          },
          "filter" :{
              "full_pinyin_no_space" : {
                  "type" : "pinyin",
                  "first_letter" : "none",
                  "padding_char" : ""
              },
              "full_pinyin_with_space" : {
                  "type" : "pinyin",
                  "first_letter" : "none",
                  "padding_char" : " "
              },
              "first_letter_pinyin" : {
                  "type" : "pinyin",
                  "first_letter" : "only",
                  "padding_char" : ""
              }
        }
    }
  },
  "mappings": {
    "books": {
      "properties": {
        "title": {
           "type":"string",
           "index":"analyzed",
           "analyzer":"custom_pinyin_analyzer",
           "search_analyzer":"custom_pinyin_analyzer",
           "boost": 10
        }
      }
    }
  }
}
}`

PUT library/books/1
{
  "title": "联想召回笔记本电源线"
}
**直接搜中文能搜出来，用拼音就不行**
GET library/books/_search
{
  "size" :10,
  "from" : 0,
    "query": {
    "multi_match": {
      "type":     "best_fields", 
      "query":    "联想",
      "fields": [ "title" ],
      "tie_breaker": 0.3,
      "minimum_should_match" : "10%"
    }
  }
}

**Comment by 651016236** [comment]
我的是es2.2.1
{
  "settings":{
    "index":{
      "number_of_shards": 5,
      "number_of_replicas": 1,
      "analysis" : {
          "analyzer" : {
              "custom_pinyin_analyzer" : {
                  "tokenizer" : "ik_max_word",
                  "filter" : ["full_pinyin_no_space","full_pinyin_with_space","first_letter_pinyin"]
              }
          },
          "filter" :{
              "full_pinyin_no_space" : {
                  "type" : "pinyin",
                  "first_letter" : "none",
                  "padding_char" : ""
              },
              "full_pinyin_with_space" : {
                  "type" : "pinyin",
                  "first_letter" : "none",
                  "padding_char" : " "
              },
              "first_letter_pinyin" : {
                  "type" : "pinyin",
                  "first_letter" : "only",
                  "padding_char" : ""
              }
        }
    }
  },
  "mappings": {
    "books": {
      "properties": {
        "title": {
           "type":"string",
           "index":"analyzed",
           "analyzer":"custom_pinyin_analyzer",
           "search_analyzer":"custom_pinyin_analyzer",
           "boost": 10
        }
      }
    }
  }
}
}

**Comment by medcl** [comment]
欢迎试试最新版本
