### ISSUE TITLE
Completion Suggest如何实现汉字、拼音、简拼搜索？

### ISSUE THREAD

**Issue by zhangweibo007** [medcl/elasticsearch-analysis-pinyin#43]
@medcl 大神，你好。我用es2.2.1版本在做关键字搜索建议的时候，想实现suggest的汉字、拼音、简拼搜索，用了各种办法都没法实现。请帮忙看一下，哪些设置错了。另：我看到前面的帖子里有设置属性类型为multi_field。但suggest没办法设置为multi_fileld啊。
1.索引设置如下
curl -X PUT 192.168.1.45:9200/musiczz/ -d '{
  "index": {
    "analysis": {
      "analyzer": {
        "pinyin_analyzer": {
          "type": "custom",
          "tokenizer": "my_pinyin",
          "filter": [
            "simple_pinyin",
            "word_delimiter"
          ]
        }
      },
      "tokenizer": {
        "my_pinyin": {
          "type": "pinyin",
          "first_letter": "none",
          "padding_char": ""
        }
      },
      "filter": {
        "simple_pinyin": {
          "type": "pinyin",
          "first_letter": "only",
          "padding_char": ""
        }
      }
    }
  }
}'

2、mapping如下：
curl -X PUT 192.168.1.45:9200/musiczz/song/_mapping -d '{
  "song" : {
        "properties" : {
            "name" : {"type" : "string"},
            "suggest" : { "type" : "completion",
                          "analyzer" : "pinyin_analyzer",
                          "search_analyzer" : "pinyin_analyzer",
                          "payloads" : true
            }
        }
    }
}'
3、索引数据
curl -X PUT '192.168.1.45:9200/musiczz/song/4?refresh=true' -d '{
    "name" : "刘德华",
    "suggest" : {
        "input": [ "刘德华"],
        "output": "刘德华",
        "payload" : { "artistId" : 2325 },
        "weight" : 34
    }
}'

4、查询suggest
1)可以查询到结果
curl -X POST '192.168.1.45:9200/musiczz/_suggest?pretty' -d '{
    "song-suggest" : {
        "text" : "liudehua",
        "completion" : {
            "field" : "suggest"
        }
    }
}'
结果如下：
{
  "_shards" : {
    "total" : 5,
    "successful" : 5,
    "failed" : 0
  },
  "song-suggest" : [ {
    "text" : "liudehua",
    "offset" : 0,
    "length" : 8,
    "options" : [ {
      "text" : "刘德华",
      "score" : 34.0,
      "payload" : {
        "artistId" : 2325
      }
    } ]
  } ]
}
2）可以查询到结果
curl -X POST '192.168.1.45:9200/musiczz/_suggest?pretty' -d '{
    "song-suggest" : {
        "text" : "刘德华",
        "completion" : {
            "field" : "suggest"
        }
    }
}'
3）简拼不能查询到结果
curl -X POST '192.168.1.45:9200/musiczz/_suggest?pretty' -d '{
    "song-suggest" : {
        "text" : "ldh",
        "completion" : {
            "field" : "suggest"
        }
    }
}'

请问，如果我要实现简拼也可以查到结果，索引应该如何设置？？？

**Comment by brucebao** [comment]
目前Completion Suggest不支持（要命的前缀查询）,用query解决吧

**Comment by occultskyrong** [comment]
index如下：
```

{
    "index": {
        "analysis": {
            "analyzer": {
                "prefix_pinyin_analyzer": {
                    "tokenizer": "keyword",
                    "filter": ["lowercase", "prefix_pinyin"]
                }
                , "full_pinyin_analyzer": {
                    "tokenizer": "keyword",
                    "filter": ["lowercase", "full_pinyin"]
                }
            },
            "tokenizer": {
                "prefix_pinyin": {
                    "type": "pinyin",
                    "first_letter": "prefix",
                    "padding_char": ""
                }
            },
            "filter": {
                "_pattern": {
                    "type": "pattern_capture",
                    "preserve_original": 1,
                    "patterns": ["([0-9])", "([a-z])"]
                }
                , "prefix_pinyin": {
                    "type": "pinyin",
                    "first_letter": "prefix",
                    "padding_char": ""
                }
                , "full_pinyin": {
                    "type": "pinyin",
                    "first_letter": "none",
                    "padding_char": ""
                }
            }
        }
    }
}
```
mapping设置：
```
          "name_prefix_pinyin": {
                "type": "completion",
                "analyzer": "prefix_pinyin_analyzer",
                "search_analyzer": "prefix_pinyin_analyzer",
                "preserve_separators": false,
                "payloads": true
            },
            "name_full_pinyin": {
                "type": "completion",
                "analyzer": "full_pinyin_analyzer",
                "search_analyzer": "full_pinyin_analyzer",
                "preserve_separators": false,
                "payloads": true
            },
```
然后用suggester去搜对应，此部分涉及到业务，可能不同
```
, body: {
            goods_prefix_suggest: {
                text: '',#搜索的key
                completion: {
                       field:"name_prefix_pinyin" #搜索的字段
                       ,size:10 #搜索的长度
                }
            }
            , goods_full_suggest: {
                text: '',#搜索的key
                completion: {..} #同上 
            }
        }
``

**Comment by zhangweibo007** [comment]
非常感谢！我试试！！

**Comment by occultskyrong** [comment]
1、这是es2.3.4下。
2、因为我是nodejs，所以用的是Elasticsearch.js中的suggest()方法，你根据你自己后端语言自己看下
https://www.elastic.co/guide/en/elasticsearch/client/javascript-api/current/api-reference.html#api-suggest
3、使用这个[completion suggester](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-suggesters-completion.html)可以和[context suggester](https://www.elastic.co/guide/en/elasticsearch/reference/current/suggester-context.html)结合使用来进行类似于query的match、term等过滤。
但是有个bug。。。。[Deleted documents show up in completion suggester](https://github.com/elastic/elasticsearch-js/issues/117)
我还没找到解决方法。。。。

**Comment by medcl** [comment]
请参见最新的README文档，使用起来更加简单
