### ISSUE TITLE
大神，多音字什么时候支持？

### ISSUE THREAD

**Issue by scorpius-wang** [medcl/elasticsearch-analysis-pinyin#44]
拼音分词现在不支持多音字啊，多音字都是默认取pinyin4j转化出来的第一个拼音，什么时候支持多音字啊？
try {
    String[] strs = PinyinHelper.toHanyuPinyinStringArray(c, format);
    if (strs != null) {
    //get first result by default
    String first_value = strs[0];
    **//TODO more than one pinyin**

**Comment by medcl** [comment]
0094ad7 目前常见的多音字基本都能处理了
