### ISSUE TITLE
这个警告信息有问题吗？

### ISSUE THREAD

**Issue by cnodoo** [medcl/elasticsearch-analysis-pinyin#48]
[WARNING] 
[WARNING] Some problems were encountered while building the effective model for org.elasticsearch:elasticsearch-analysis-pinyin:jar:1.7.4
[WARNING] 'dependencies.dependency.systemPath' for net.sourceforge.pinyin4j:pinyin4j:jar should not point at files within the project directory, ${basedir}/lib/pinyin4j-2.5.0.jar will be unresolvable by dependent projects @ line 64, column 25
[WARNING] 
[WARNING] It is highly recommended to fix these problems because they threaten the stability of your build.
[WARNING] 
[WARNING] For this reason, future Maven versions might no longer support building such malformed projects.
[WARNING]

**Comment by medcl** [comment]
可以忽略
