### ISSUE TITLE
请问PinyinTokenFilter 中first_letter 设为prefix有什么用处

### ISSUE THREAD

**Issue by ttjslbz** [medcl/elasticsearch-analysis-pinyin#49]
您好，在拜读代码。
我有一个疑问，在PinyinTokenFilter中如果first_letter设为prefix，那么每个字的拼音前会前缀其拼音的声母。例如“刘”会被拼音转为liu 然后最终产生的termAttribute是“lliu”。这个操作的意义是神马？
初次接触soundex search，请多指教。

**Comment by medcl** [comment]
prefix一般是结合padding_char，然后再结合word-delimiter 来进行前缀查询，如分成l和liu，分成lliu没有意义

**Comment by occultskyrong** [comment]
ps：prefix貌似不是声母，而是拼音的第一个字母，比如“产品”是“cp”而不是“chp”。。。
just like：
```
/_analyze?analyzer=prefix_pinyin_analyzer&pretty&text=产品
```
![image](https://cloud.githubusercontent.com/assets/8370006/17576336/12db2eca-5fa4-11e6-999a-dbb654f1b732.png)

**Comment by medcl** [comment]
只是首字母而已

**Comment by medcl** [comment]
最新版本已经修改配置方式
