### ISSUE TITLE
多音字拼音和首拼搜索顺序的问题

### ISSUE THREAD

**Issue by callmejea** [medcl/elasticsearch-analysis-pinyin#50]
各位大神好
比如: 银行(yin xing) 香桔(xiang jie)
这样输入的是 yinhang 那么查询的结果完全是不正确的, 
看了上面的提问, 这个问题忽略
---------------------以下----------
首拼: 香桔市 (xjs)   锦绣世界(jxsj) 这个时候, 锦绣世界就排到了 香桔市的前面去了, 因为词频上多了一个j

怎么样才能用完整的顺序(xjs) 去搜首拼呢? 没有找到

求助

**Comment by occultskyrong** [comment]
1、多音字暂不支持。这个我也不知道咋办。。除非你自己整理个自定义字典。。
2、首拼可以prefix试一下。。结合completion suggester。。
类似#43中。。。。

**Comment by callmejea** [comment]
@occultskyrong  我这暂时不用 pinyin 去做了, 因为实在是解决不了多音字的问题, 目前 造轮子造了个 汉字转多音字的, 然后去搜索拼音-首拼, 确实是用 phrase_prefix 来搜索的, 无奈了

**Comment by occultskyrong** [comment]
我尝试过[match_phrase_prefix](https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-match-query.html#query-dsl-match-query-phrase-prefix)。。
但有个问题跟我的需求不一样。。。
比如搜“可口可乐”会在中段位置命中“太古可口可乐”，而我想要的只是“可口可乐”开头的doc。。
惆怅啊。。。

**Comment by callmejea** [comment]
使用
```php
array(
        'multi_match' => array(
            'query'  => array('这里是拼音字母'),
            'type'   => 'phrase_prefix',
            'fields' => array('拼音字段'),
        ),
    );
```
我是这么用的, 没有出现你所说的情况, 匹配到的一定是以 query 里开头的

**Comment by occultskyrong** [comment]
ok,我试一下你这个。。

**Comment by BearKid** [comment]
> 我尝试过[match_phrase_prefix](https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-match-query.html#query-dsl-match-query-phrase-prefix)。。
> 但有个问题跟我的需求不一样。。。
> 比如搜“可口可乐”会在中段位置命中“太古可口可乐”，而我想要的只是“可口可乐”开头的doc。。
> 惆怅啊。。。

你提到的这个需求知道怎么解决吗？
输入“kekoukl"，用match_phrase会匹配到句子”可口可乐“和”太古可口可乐“，我希望句子”可口可乐“排在前面，或者压根不让”太古可口可乐“出现，必须要符合”右模糊匹配“。
match_phrase_prefix方法定义的所谓前缀匹配效果并不是”右模糊匹配“

**Comment by BearKid** [comment]
@occultskyrong @callmejea 我上面提及的疑问
