### ISSUE TITLE
Not able to plugin install

### ISSUE THREAD

**Issue by ryancheung** [medcl/elasticsearch-analysis-pinyin#58]
I'm using elasticsearch v2.1.1. `./plugin install medcl/elasticsearch-analysis-pinyin` would fail.

**Comment by medcl** [comment]
install by `plugin` currently not supported yet, please go to release page, download specify version.

**Comment by ryancheung** [comment]
@medcl OK. I'm new to Elasticsearch. Could you tell me how to install plugin with the specific version?
