### ISSUE TITLE
为什么没有v1.7.5版本呢？

### ISSUE THREAD

**Issue by lyroge** [medcl/elasticsearch-analysis-pinyin#60]
本来想试试这个pinyin插件，我对应的es是2.3.5， 看说明是需要v1.7.5 release支持。 不过唯独没有这个版本，咋回事？？？

**Comment by ryancheung** [comment]
@lyroge v1.7.5 我编译试过了，完全不能用（我也是醉了，居然没有提示），估计也就是为什么没有2.3.5 es版本支持。目前我用的是es5 alpha5 ，这个好用

**Comment by lyroge** [comment]
可是我用的es2.3.5啊， 用哪个es5不行。 都升级一下？

**Comment by medcl** [comment]
不好意思，for es2.3.5的v1.7.5忘记打标签了，使用方式和之前版本是一样的， @ryancheung 完全不能用是什么意思？

**Comment by medcl** [comment]
https://github.com/medcl/elasticsearch-analysis-pinyin/releases/tag/v1.7.5

**Comment by lyroge** [comment]
cool . thanks

**Comment by ryancheung** [comment]
@medcl 就是拼音不能分词，只有一个token。比如：你是我的小苹果，anyalize出来结果只有 nishiwodexiaopingguo 一个token

**Comment by ryancheung** [comment]
@lyroge es5 就 docker 启动时得加个参数，其他搜索功能正常

**Comment by medcl** [comment]
有参数可以控制

Ryan Cheung <notifications@github.com>于2016年8月26日 周五下午5:11写道：

**Comment by ryancheung** [comment]
是的
