### ISSUE TITLE
加入拼音之后出现了一些问题。

### ISSUE THREAD

**Issue by Aibric** [medcl/elasticsearch-analysis-pinyin#61]
比如我商品名称里有 “测试安全帽”。还有“翻毛透气安全鞋”，我在搜索的 “安全帽” 的时候，翻毛透气安全鞋也出来了，是不是多音字的原因呢？

**Comment by medcl** [comment]
匹配了安全，你用的什么查询，你试试设置default_operator=AND,让条件都匹配的才出来

**Comment by Aibric** [comment]
我用的就是这个and 呢。
```
"query_string" => [
    "fields" => [
	"goodsName",
	"goodsSn",
	"goodsName.pinyin",
	"goodsName.first_letter"
    ],
    "query" => $k,
    "default_operator" => "AND"
], 

```

**Comment by medcl** [comment]
analyzer怎么定义的

**Comment by lyroge** [comment]
结合pin及ik插件后， 对中文的分词后面出现空格， 如分析词汇韩国， 解析的token为"token": "han ","token": "guo "  后面都含有空格， 已经配置了trim tokenizer 。

 但是不管用。 配置的分词器如下： 
     ik_pinyin:
          type: custom
          tokenizer: ik
          filter:
            - pinyin
            - lowercase

什么原因呢？  @medcl

**Comment by medcl** [comment]
@lyroge 样本和测试的请求有么，发我测试一下

**Comment by Aibric** [comment]
@medcl 这个analyzer 应该是按照之前你在 http://elasticsearch.cn，上面写的去做的。
```
"analysis": {
    "filter": {
        "full_pinyin_no_space": {
            "padding_char": "",
            "type": "pinyin",
            "first_letter": "none"
        },
        "my_edge_ngram_tokenizer": {
            "token_chars": [
                "letter" ,
                "digit"
            ],
            "min_gram": "2",
            "type": "edgeNGram",
            "max_gram": "5"
        },
        "remove_whitespace": {
            "pattern": "\s+",
            "type": "pattern_replace",
            "replacement": ""
        },
        "full_pinyin_with_space": {
            "padding_char": " ",
            "type": "pinyin",
            "first_letter": "none"
        }
    },
    "analyzer": {
        "my_pinyin_analyzer": {
            "filter": [
                "full_pinyin_no_space"
            ],
            "tokenizer": "keyword"
        },
        "ngram_pinyin_analyzer": {
            "filter": [
                "full_pinyin_with_space",
                "word_delimiter",
                "shingle" ,
                "remove_whitespace"
            ],
            "tokenizer": "keyword"
        }
```

**Comment by medcl** [comment]
@Aibric 你用的什么版本啊？
5.0的不能照着用

**Comment by medcl** [comment]
@Aibric 第一个安全帽的为什么会匹配出来是因为，拼音都匹配上了，『毛，安全』和『安全帽』的拼音组合是一样的。
可以试试换个查询的方式就行，用phrase，控制位置

`

GET medcl/type/_search
{
  "query": {
    "query_string": {
      "default_field": "goodsName",
      "query": "\"安全帽\""
    }
  },
  "explain": false
}

GET medcl/type/_search
{
  "query": {
    "match_phrase": {
    "goodsName" : {
            "query" : "安全帽",
            "analyzer" : "search_pinyin_analyzer"
        }
    }
  }
}
`

**Comment by medcl** [comment]
完整例子
```
DELETE medcl

PUT medcl
{
      "index": {
        "analysis": {
          "analyzer": {
            "index_pinyin_analyzer": {
              "tokenizer": "index_pinyin"
            },
             "search_pinyin_analyzer": {
              "tokenizer": "search_pinyin"
            }
          },
          "tokenizer": {
            "index_pinyin": {
              "keep_none_chinese_in_first_letter": "true",
              "lowercase": "true",
              "keep_original": "true",
              "keep_first_letter": "true",
              "trim_whitespace": "true",
              "type": "pinyin",
              "keep_none_chinese": "true",
              "limit_first_letter_length": "16",
              "keep_full_pinyin": "true"
            },
             "search_pinyin": {
              "keep_none_chinese_in_first_letter": "false",
              "lowercase": "true",
              "keep_original": "false",
              "keep_first_letter": "false",
              "trim_whitespace": "true",
              "type": "pinyin",
              "keep_none_chinese": "false",
              "limit_first_letter_length": "16",
              "keep_full_pinyin": "true"
            }
          }
        },
        "number_of_shards": "5",
        "number_of_replicas": "1"
      }
}


POST medcl/type/_mapping
{
  "properties": {
    "goodsName":{
      "type": "text",
      "analyzer": "index_pinyin_analyzer",
      "search_analyzer": "search_pinyin_analyzer"
    }
  }
}

POST medcl/type/1
{
  "goodsName":"测试安全帽"
}

POST medcl/type/2
{
  "goodsName":"翻毛透气安全鞋"
}

POST medcl/_analyze
{
  "text":"测试安全帽",
  "analyzer":"search_pinyin_analyzer"
}

GET medcl/type/_search
{
  "query": {
    "query_string": {
      "default_field": "goodsName",
      "query": "\"安全帽\""
    }
  },
  "explain": false
}

GET medcl/type/_search
{
  "query": {
    "match_phrase": {
    "goodsName" : {
            "query" : "安全帽",
            "analyzer" : "search_pinyin_analyzer"
        }
    }
  }
}

```

**Comment by medcl** [comment]
@lyroge 你的问题，可以把去重空格的filter放在最后，按顺序执行的

**Comment by Aibric** [comment]
非常感谢@medcl ，我用的是elasticsearch-2.3.3  Pinyin 1.7.5 还没开始用 5.0，这两天有时间试下。
```
"goodsName" : {
       "query" : "安全帽",
      "analyzer" : "search_pinyin_analyzer"
}
```
elasticsearch-2.3.3 对，"analyzer" : "search_pinyin_analyzer"  这部分写法好象不支持。

**Comment by Aibric** [comment]
@medcl 你写的DEMO应该是 5.0的。我用的不是额。。。怎么解决这个问题啊，本人菜鸟一枚。谢谢。

**Comment by medcl** [comment]
@Aibric 5.0的可以试试最新的，已经 fix 了 position

**Comment by medcl** [comment]
2.4.1也更新支持了

**Comment by mbinge** [comment]
"index_pinyin": {
              "keep_none_chinese_in_first_letter": "true",
              "lowercase": "true",
              "keep_original": "true",
              "keep_first_letter": "true",
              "trim_whitespace": "true",
              "type": "pinyin",
              "keep_none_chinese": "true",
              "limit_first_letter_length": "16",
              "keep_full_pinyin": "true"
            }

这堆配置在1.8.0里面可以用么？

跟"first_letter"，"padding_char"什么关系呢？

建议把readme更新下

**Comment by medcl** [comment]
@mbinge 只有1.8.1才有

**Comment by Neo-WU** [comment]
如何支持全拼搜呢@medcl

**Comment by medcl** [comment]
@Neo-WU  参数："keep_full_pinyin": "true"

**Comment by Neo-WU** [comment]
"analysis":{
			"filter":{
				"my_synonym_filter":{
				"type": "synonym",
				"synonyms_path": "analysis/synonym.txt"
				}
			},
			"analyzer":{
				"ik_syno":{
					"type": "custom",
					"tokenizer": "ik_max_word",
					"filter": ["my_synonym_filter"]
				},
				"ik_syno_smart":{
					"type": "custom",
					"tokenizer": "ik_smart",
					"filter": ["my_synonym_filter"]
				},
				"pinyin_analyzer" : {
					"tokenizer" : "my_pinyin"
				}
			},
			"tokenizer" : {
				"my_pinyin" : {
					"type" : "pinyin",
					"keep_separate_first_letter" : false,
					"keep_full_pinyin" : true,
					"keep_original" : true,
					"limit_first_letter_length" : 16,
					"lowercase" : true
				}
			}
		}

字段的mapping
"hotel_name":{
					"type":"string",
					"boost":10,
					"fields":{
						"cn":{
							"type":"string",
							"index":"analyzed",
							"analyzer":"ik_syno"
						},
						"pinyin":{
							"type":"string",
							"index":"analyzed",
							"analyzer":"pinyin_analyzer"
						}
					}

				},



搜索
"query":{

			"multi_match": {
			"query":"quanpinyin",
			"type":"best_fields", 
			"operator":	"or",
			"fields":[ "hotel_name.cn", "hotel_name.pinyin" ]
		}
				
	},


这个搜索条件搜不到呢，是不是那里配置的不合适。
@medcl

**Comment by medcl** [comment]
@Neo-WU  找到 bug 了，你重新下载试试

**Comment by medcl** [comment]
fell free to reopen
