### ISSUE TITLE
使用pinyin和ik后，查询结果有问题

### ISSUE THREAD

**Issue by wuxinchaliu** [medcl/elasticsearch-analysis-pinyin#64]
您好，medcl, 看了您的文档说明，配置一下ik和pinyin，搜索梁朝伟出现问题，pinyin 1.7.5
index:

curl -XPUT http://localhost:9200/medcl/ -d'
{
    "index" : {
        "analysis" : {
            "analyzer" : {
                "custom_pinyin_analyzer" : {
                    "tokenizer" : "ik_smart",
                    "filter" : ["full_pinyin_no_space","full_pinyin_with_space","first_letter_pinyin","word_delimiter","nGram"]
                }
            },
            "filter" :{
                "full_pinyin_no_space" : {
                    "type" : "pinyin",
                    "first_letter" : "none",
                    "padding_char" : ""
                },
                "full_pinyin_with_space" : {
                    "type" : "pinyin",
                    "first_letter" : "none",
                    "padding_char" : " "
                },
                "first_letter_pinyin" : {
                    "type" : "pinyin",
                    "first_letter" : "only",
                    "padding_char" : ""
               }
           }
        }
    }
}'

mapping配置如下：

curl -XPOST http://localhost:9200/medcl/resource/_mapping -d'
{
    "resource": {
    "properties": {
        "name": {
            "type": "multi_field",
                "fields": {
                "name": {
                    "type": "string",
                        "store": "no",
                        "term_vector": "with_positions_offsets",
                        "analyzer": "custom_pinyin_analyzer",
                        "boost": 10
                    },
                    "primitive": {
                    "type": "string",
                        "store": "yes",
                        "analyzer": "keyword"
                    }
                }
            }
        }
    }
}'

curl -XPOST localhost:9200/medcl/resource/1 -d '{"name":"刘德华"}'
curl -XPOST localhost:9200/medcl/resource/2 -d '{"name":"我非常崇拜刘德华"}'
curl -XPOST localhost:9200/medcl/resource/3 -d '{"name":"刘德华是一个受人尊敬的人"}'
curl -XPOST localhost:9200/medcl/resource/4 -d '{"name":"周润发是一个受人尊敬的人"}'
curl -XPOST localhost:9200/medcl/resource/5 -d '{"name":"梁朝伟是一个受人尊敬的人"}'
curl -XPOST localhost:9200/medcl/resource/6 -d '{"name":"梁朝伟去厦门拍戏"}'

然后搜索http://localhost:9200/medcl/resource/_search?q=name:liude
http://localhost:9200/medcl/resource/_search?q=name:liu
http://localhost:9200/medcl/resource/_search?q=name:liudehua
都出现如下结果，期望，前面3个都是刘德华
"hits":[
            {
                "_index":"medcl",
                "_type":"resource",
                "_id":"2",
                "_score":16.67528,
                "_source":{
                    "name":"我非常崇拜刘德华"
                }
            },
            {
                "_index":"medcl",
                "_type":"resource",
                "_id":"1",
                "_score":9.62926,
                "_source":{
                    "name":"刘德华"
                }
            },
            {
                "_index":"medcl",
                "_type":"resource",
                "_id":"6",
                "_score":6.887643,
                "_source":{
                    "name":"梁朝伟去厦门拍戏"
                }
            },
            {
                "_index":"medcl",
                "_type":"resource",
                "_id":"4",
                "_score":6.1695423,
                "_source":{
                    "name":"周润发是一个受人尊敬的人"
                }
            },
            {
                "_index":"medcl",
                "_type":"resource",
                "_id":"3",
                "_score":5.235542,
                "_source":{
                    "name":"刘德华是一个受人尊敬的人"
                }
            },
            {
                "_index":"medcl",
                "_type":"resource",
                "_id":"5",
                "_score":2.228907,
                "_source":{
                    "name":"梁朝伟是一个受人尊敬的人"
                }
            }
        ]
    }

同样搜索梁朝伟，排在最前面的2个不是梁朝伟，@medcl,这个是我配置有问题吗？
http://localhost:9200/medcl/resource/_search?q=name:liang
http://localhost:9200/medcl/resource/_search?q=name:liangchaowei
"hits":[
            {
                "_index":"medcl",
                "_type":"resource",
                "_id":"6",
                "_score":27.162048,
                "_source":{
                    "name":"梁朝伟去厦门拍戏"
                }
            },
            {
                "_index":"medcl",
                "_type":"resource",
                "_id":"2",
                "_score":17.544949,
                "_source":{
                    "name":"我非常崇拜刘德华"
                }
            },
            {
                "_index":"medcl",
                "_type":"resource",
                "_id":"5",
                "_score":7.7484355,
                "_source":{
                    "name":"梁朝伟是一个受人尊敬的人"
                }
            },
            {
                "_index":"medcl",
                "_type":"resource",
                "_id":"4",
                "_score":6.061264,
                "_source":{
                    "name":"周润发是一个受人尊敬的人"
                }
            },
            {
                "_index":"medcl",
                "_type":"resource",
                "_id":"1",
                "_score":1.8978631,
                "_source":{
                    "name":"刘德华"
                }
            },
            {
                "_index":"medcl",
                "_type":"resource",
                "_id":"3",
                "_score":1.7874237,
                "_source":{
                    "name":"刘德华是一个受人尊敬的人"
                }
            }
        ]
    }

**Comment by medcl** [comment]
http://localhost:9200/medcl/resource/_search?q=name:liang&default_operator=AND

**Comment by wuxinchaliu** [comment]
@medcl 加上default_operator=AND之后，查询结果没有变化
http://localhost:9200/medcl/resource/_search?q=name:liang&default_operator=AND
http://localhost:9200/medcl/resource/_search?q=name:liangchaowei&default_operator=AND
还是这样的
"hits":[
            {
                "_index":"medcl",
                "_type":"resource",
                "_id":"6",
                "_score":27.162048,
                "_source":{
                    "name":"梁朝伟去厦门拍戏"
                }
            },
            {
                "_index":"medcl",
                "_type":"resource",
                "_id":"2",
                "_score":17.544949,
                "_source":{
                    "name":"我非常崇拜刘德华"
                }
            },
            {
                "_index":"medcl",
                "_type":"resource",
                "_id":"5",
                "_score":7.7484355,
                "_source":{
                    "name":"梁朝伟是一个受人尊敬的人"
                }
            },
            {
                "_index":"medcl",
                "_type":"resource",
                "_id":"4",
                "_score":6.061264,
                "_source":{
                    "name":"周润发是一个受人尊敬的人"
                }
            },
            {
                "_index":"medcl",
                "_type":"resource",
                "_id":"1",
                "_score":1.8978631,
                "_source":{
                    "name":"刘德华"
                }
            },
            {
                "_index":"medcl",
                "_type":"resource",
                "_id":"3",
                "_score":1.7874237,
                "_source":{
                    "name":"刘德华是一个受人尊敬的人"
                }
            }
        ]
    }

**Comment by wuxinchaliu** [comment]
多谢 @medcl ,问题解决了
curl -XGET localhost:9200/medcl/resource/_search?pretty -d '{"query":{"common":{"name":{"query":"liang","low_freq_operator":"and"}}}}'

**Comment by wanming** [comment]
@wuxinchaliu 用了你的办法，搜索结果为空。。上面其他例子返回结果是跟你一样的，这是为啥呢

**Comment by zhoujiayu** [comment]
你好，es中的数据我存对应中文的全拼和简拼，是否用了拼音分词器就可以不用这两列的数据，还有具体配置拼音分词器怎么配置。看了大多数都是curl 这种直接，配置文件中，求教，谢谢

**Comment by medcl** [comment]
@zhoujiayu 是的，不用在外面单独存一份拼音了

**Comment by zhoujiayu** [comment]
@medcl  之前的问题解决了，elasticsearch-analysis-pinyin  用这个插件，怎么实现拼音检索命中的汉字高亮显示，汉字检索已经用了ik分词器，可以怎么解决，映射文件该如何配置。谢谢

**Comment by medcl** [comment]
@zhoujiayu 不支持高亮

**Comment by medcl** [comment]
```
➜  conference-site git:(master) ✗ curl -XPOST http://localhost:9200/medcl/_search -d'         
{
    "query" : {
        "match" : {
           "name.pinyin":"liu德" 
        }
    },  "highlight" : {
        "fields" : {
            "name.pinyin" : {}
        }
    }

}'
{"took":35,"timed_out":false,"_shards":{"total":5,"successful":5,"failed":0},"hits":{"total":1,"max_score":5.4359555,"hits":[{"_index":"medcl","_type":"folks","_id":"andy","_score":5.4359555,"_source":{"name":"刘德华1231231xx"},"highlight":{"name.pinyin":["<em>刘</em><em>德</em>华1231231xx"]}}]}}%   
```

**Comment by iris-8** [comment]
@medcl 库中存有name1=京东的数据，怎样才能在搜索"懂"的时候不会搜出京东
curl -XPOST localhost:9200/medc5/type5/_search?pretty -d'
{
  "query": {
    "multi_match": {
	"query":    "懂", 
       "fields": [
        "name1.ik^1000","name1.pinyin"
      ]
    }
  }
}'
