### ISSUE TITLE
i use v1.7.1 ,i modify the code and i want to mvn package self？

### ISSUE THREAD

**Issue by wusi05** [medcl/elasticsearch-analysis-pinyin#65]
i modify some code,and want to modify code by mvn clear package ,it is wrong, as following:

WARNING] Some problems were encountered while building the effective model for org.elasticsearch:elasticsearch-analysis-pinyin:jar:1.7.1
[WARNING] 'dependencies.dependency.systemPath' for net.sourceforge.pinyin4j:pinyin4j:jar should not point at files within the project directory, ${basedir}/lib/pinyin4j-2.5.0.jar will be unresolvable by dependent projects @ line 64, column 25
[WARNING]
[WARNING] It is highly recommended to fix these problems because they threaten the stability of your build.
[WARNING]
[WARNING] For this reason, future Maven versions might no longer support building such malformed projects.

so how can i package myself  
thank you a lot

**Comment by medcl** [comment]
https://github.com/medcl/elasticsearch-analysis-pinyin/releases
