### ISSUE TITLE
create index , status： 400

### ISSUE THREAD

**Issue by mysterytree** [medcl/elasticsearch-analysis-pinyin#66]
service_1 | org.elasticsearch.indices.IndexCreationException: [users_development_20160908153123308] failed to create index
service_1 | 	at org.elasticsearch.indices.IndicesService.createIndex(IndicesService.java:338)
service_1 | 	at org.elasticsearch.cluster.metadata.MetaDataCreateIndexService$2.execute(MetaDataCreateIndexService.java:371)
service_1 | 	at org.elasticsearch.cluster.service.InternalClusterService$UpdateTask.run(InternalClusterService.java:374)
service_1 | 	at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.runAndClean(PrioritizedEsThreadPoolExecutor.java:204)
service_1 | 	at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.run(PrioritizedEsThreadPoolExecutor.java:167)
service_1 | 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
service_1 | 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
service_1 | 	at java.lang.Thread.run(Thread.java:745)
service_1 | Caused by: org.elasticsearch.ElasticsearchIllegalArgumentException: failed to find token filter type [pinyin] for [prefix_pinyin]
service_1 | 	at org.elasticsearch.index.analysis.AnalysisModule.configure(AnalysisModule.java:249)
service_1 | 	at org.elasticsearch.common.inject.AbstractModule.configure(AbstractModule.java:60)
service_1 | 	at org.elasticsearch.common.inject.spi.Elements$RecordingBinder.install(Elements.java:204)
service_1 | 	at org.elasticsearch.common.inject.spi.Elements.getElements(Elements.java:85)
service_1 | 	at org.elasticsearch.common.inject.InjectorShell$Builder.build(InjectorShell.java:130)
service_1 | 	at org.elasticsearch.common.inject.InjectorBuilder.build(InjectorBuilder.java:99)
service_1 | 	at org.elasticsearch.common.inject.InjectorImpl.createChildInjector(InjectorImpl.java:131)
service_1 | 	at org.elasticsearch.common.inject.ModulesBuilder.createChildInjector(ModulesBuilder.java:69)
service_1 | 	at org.elasticsearch.indices.IndicesService.createIndex(IndicesService.java:336)
service_1 | 	... 7 more
service_1 | Caused by: org.elasticsearch.common.settings.NoClassSettingsException: Failed to load class setting [type] with value [pinyin]
service_1 | 	at org.elasticsearch.common.settings.ImmutableSettings.loadClass(ImmutableSettings.java:476)
service_1 | 	at org.elasticsearch.common.settings.ImmutableSettings.getAsClass(ImmutableSettings.java:464)
service_1 | 	at org.elasticsearch.index.analysis.AnalysisModule.configure(AnalysisModule.java:239)
service_1 | 	... 15 more
service_1 | Caused by: java.lang.ClassNotFoundException: org.elasticsearch.index.analysis.pinyin.PinyinTokenFilterFactory
service_1 | 	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
service_1 | 	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
service_1 | 	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
service_1 | 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
service_1 | 	at org.elasticsearch.common.settings.ImmutableSettings.loadClass(ImmutableSettings.java:474)
service_1 | 	... 17 more

**Comment by medcl** [comment]
service_1 | Caused by: org.elasticsearch.ElasticsearchIllegalArgumentException: failed to find token filter type [pinyin] for [prefix_pinyin]


es 什么版本？
mapping 配置发一下

**Comment by mysterytree** [comment]
@medcl 找到原因了  权限问题  没read权限  谢了
