### ISSUE TITLE
java 怎么调用

### ISSUE THREAD

**Issue by zhangchc** [medcl/elasticsearch-analysis-pinyin#67]
QueryStringQueryBuilder queryBuilder = new QueryStringQueryBuilder("huawang");//查询的词
        queryBuilder.field(GoodsEnum.brandName.name());

我模拟了一下 写了上面一段代码 查出来结果根本匹配不上
{
  "from": 0,
  "size": 10,
  "query": {
    "query_string": {
      "query": "huawang",
      "fields": [
        "brandName"
      ]
    }
  },
  "explain": true,
  "sort": [
    {
      "pdtCreateTime": {
        "order": "asc"
      }
    }
  ]
}

**Comment by medcl** [comment]
master 版本已支持 pinyin 的切分
