### ISSUE TITLE
elasticsearch 5.0.0beta1

### ISSUE THREAD

**Issue by heartszhang** [medcl/elasticsearch-analysis-pinyin#68]
elasticsearch-plugin install file:///....pinyin-5.0.0-beta1.zip
-> Downloading file:///home/zion/ws/elasticsearch-analysis-pinyin/target/releases/elasticsearch-analysis-pinyin-5.0.0-beta1.zip
[=================================================] 100%   
ERROR: `elasticsearch` directory is missing in the plugin zip

**Comment by medcl** [comment]
解压到plugins目录就行了，哪有这么麻烦
hearts <notifications@github.com>于2016年9月30日 周五上午4:35写道：
