### ISSUE TITLE
拼音如何切分

### ISSUE THREAD

**Issue by zerix** [medcl/elasticsearch-analysis-pinyin#69]
当搜索的关键字为拼音词语时，是否有办法按字切分搜索？

比如我搜索“zhuozi"，是否可以切分为"zhuo" "zi"两个字然后再去搜索呢？

谢谢。

**Comment by zerix** [comment]
好吧 lc_pinyin有这个功能，希望作者能快速更新，增加拼音分词功能啊。

**Comment by medcl** [comment]
嗯，没问题，也欢迎提交pr
zerix <notifications@github.com>于2016年10月8日 周六上午10:54写道：

**Comment by medcl** [comment]
master 已支持pinyin 的切分
