### ISSUE TITLE
可否把最新插件支持一下es 1.x？

### ISSUE THREAD

**Issue by localtest** [medcl/elasticsearch-analysis-pinyin#76]
可否把最新插件支持一下es 1.x，以满足老版本es需要？

**Comment by medcl** [comment]
1.x太老了，es 都已经不维护了，建议升级到2.x或者5.x，1.x 我可以支持一个最新的版本

**Comment by localtest** [comment]
辛苦Medcl 支持一下1.x的最新版本！

2016-12-28 21:50 GMT+08:00 Medcl <notifications@github.com>:

**Comment by medcl** [comment]
https://github.com/medcl/elasticsearch-analysis-pinyin/releases/tag/v1.3.3
