### ISSUE TITLE
Why did the word result not the same as yours?

### ISSUE THREAD

**Issue by fanyoujian** [medcl/elasticsearch-analysis-pinyin#78]
curl -XPUT http://localhost:9200/medcl3/ -d'
{
    "index" : {
        "analysis" : {
            "analyzer" : {
                "pinyin_analyzer" : {
                    "tokenizer" : "my_pinyin"
                    }
            },
            "tokenizer" : {
                "my_pinyin" : {
                    "type" : "pinyin",
                    "keep_separate_first_letter" : false,
                    "keep_full_pinyin" : true,
                    "keep_original" : true,
                    "limit_first_letter_length" : 16,
                    "lowercase" : true
                }
            }
        }
    }
}'

result

"tokens": [
{
"token": "l",
"start_offset": 0,
"end_offset": 3,
"type": "word",
"position": 0
}
,
{
"token": "ld",
"start_offset": 0,
"end_offset": 3,
"type": "word",
"position": 0
}
,
{
"token": "d",
"start_offset": 0,
"end_offset": 3,
"type": "word",
"position": 0
}

**Comment by medcl** [comment]
can you give me the full recurrence script, Thanks
