### ISSUE TITLE
和shingle filter 合用会报错

### ISSUE THREAD

**Issue by OuHangKresnik** [medcl/elasticsearch-analysis-pinyin#79]
config:

        "settings" : {
            "analysis" : {
                "analyzer" : {
                    "pinyin_analyzer" : {
                        "tokenizer" : "my_pinyin",
                        "filter" : [ "shingle" ]
                        }
                },
                "tokenizer" : {
                    "my_pinyin" : {
                        "type" : "pinyin",
                        "remove_duplicated_term" : true,
                        "keep_first_letter" : true,
                        "none_chinese_pinyin_tokenize" : false,
                        "keep_none_chinese" : false, 
                        "keep_none_chinese_together" : false,
                        "none_chinese_pinyin_tokenize" : false,
                        "keep_separate_first_letter" : false,
                        "keep_full_pinyin" : true,
                        "keep_original" : false,
                        "limit_first_letter_length" : 32,
                        "lowercase" : true,
                        "trim_whitespace" : true
                    }
                }
            }
        }

当输入是“嚖嚗嚘啮嚚嚛嚜嚝嚞嚟嚠嚡嚢嚣嚤呖嚧咙嚩咙嚧嚪嚫嚬嚭嚯嚰嚱亸喾嚵嘤嚷嚸嚹嚺嚻嚼嚽嚾嚿啭嗫嚣囃囄冁囆囇呓囊囋囍囎囏囐” 就会失败，而单独使用my_pinyin, 则会成功。
把输入变短，比如“嚖嚗嚘啮嚚嚛嚜嚝嚞嚟嚠嚡嚢嚣嚤呖嚧咙嚩咙嚧嚪嚫嚬嚭嚯嚰嚱亸喾”，也会成功
输入有重复字，比如“嚖嚗嚘啮嚚嚖嚗嚘啮嚚嚖嚗嚘啮嚚嚖嚗嚘啮嚚嚖嚗嚘啮嚚嚖嚗嚘啮嚚嚖嚗嚘啮嚚嚖嚗嚘啮嚚嚖嚗嚘啮嚚嚖嚗嚘啮嚚嚖嚗嚘啮嚚” 会成功

报错是：

org.elasticsearch.transport.RemoteTransportException:         [dataqa_elastic_search_node][192.168.5.7:9300][indices:admin/analyze[s]]
        Caused by: java.lang.IllegalArgumentException: startOffset must be non-negative, and endOffset must be >= startOffset, startOffset=34,endOffset=32
	        at org.apache.lucene.analysis.tokenattributes.PackedTokenAttributeImpl.setOffset(PackedTokenAttributeImpl.java:107) ~[lucene-core-6.3.0.jar:6.3.0 a66a44513ee8191e25b477372094bfa846450316 - shalin - 2016-11-02 19:47:11]
	        at org.apache.lucene.analysis.shingle.ShingleFilter.incrementToken(ShingleFilter.java:345) ~[lucene-analyzers-common-6.3.0.jar:6.3.0 a66a44513ee8191e25b477372094bfa846450316 - shalin - 2016-11-02 19:47:43]
	        at org.elasticsearch.action.admin.indices.analyze.TransportAnalyzeAction.simpleAnalyze(TransportAnalyzeAction.java:222) ~[elasticsearch-5.1.1.jar:5.1.1]

当

**Comment by medcl** [comment]
shingle 适合的是分词产生的 term 没有重叠的场景，拼音分词有重叠，shingle 就会出错，所以，你只需要配置拼音插件不产生冗余重叠的 term 就可以了，如下：

```
curl -XPUT http://localhost:9200/medcl6/ -d'
{
    "index" : {
        "analysis" : {
            "analyzer" : {
                "pinyin_analyzer" : {
                      "tokenizer" : "my_pinyin",
                    "filter" : [ "shingle" ]
                    }
            },
            "tokenizer" : {
                "my_pinyin" : {
                   "type" : "pinyin",
                    "remove_duplicated_term" : false,
                    "keep_first_letter" : false,
                    "none_chinese_pinyin_tokenize" : false,
                    "keep_none_chinese" : false, 
                    "keep_none_chinese_together" : false,
                    "none_chinese_pinyin_tokenize" : false,
                    "keep_separate_first_letter" : false,
                    "keep_full_pinyin" : true,
                    "keep_original" : false,
                    "limit_first_letter_length" : 32,
                    "lowercase" : true,
                    "trim_whitespace" : true
                }
            }
        }
    }
}'

http://localhost:9200/medcl6/_analyze?text=刘德华&analyzer=pinyin_analyzer&pretty=true
```
结果
```
{
  "tokens" : [ {
    "token" : "liu",
    "start_offset" : 0,
    "end_offset" : 1,
    "type" : "word",
    "position" : 1
  }, {
    "token" : "liu de",
    "start_offset" : 0,
    "end_offset" : 2,
    "type" : "shingle",
    "position" : 1
  }, {
    "token" : "de",
    "start_offset" : 1,
    "end_offset" : 2,
    "type" : "word",
    "position" : 2
  }, {
    "token" : "de hua",
    "start_offset" : 1,
    "end_offset" : 3,
    "type" : "shingle",
    "position" : 2
  }, {
    "token" : "hua",
    "start_offset" : 2,
    "end_offset" : 3,
    "type" : "word",
    "position" : 3
  } ]
}

```

**Comment by OuHangKresnik** [comment]
(⊙o⊙)哦，这样的啊，谢谢
