### ISSUE TITLE
拼音分词用拼音搜索时分出现在空格

### ISSUE THREAD

**Issue by liwei66** [medcl/elasticsearch-analysis-pinyin#80]
您好，
我的索引是：
{
"settings": {
 
  "index": {
    "analysis": {
      "analyzer": {
        "pinyin_analyzer": {
          "tokenizer": "my_pinyin"
        }
      },
      "tokenizer": {
        "my_pinyin": {
           "type" : "pinyin",
           "keep_full_pinyin":false,
           "keep_separate_first_letter" : false,
           "keep_joined_full_pinyin" : true,
           "keep_original" : true,
           "limit_first_letter_length" : 16,
           "lowercase" : true,
           "keep_first_letter":false
       }
      }
    }
  }
 
},
"mappings": {
  "hcmpersoninfotrace": {
    "properties": {
      "hcmPersName": {
        "type": "keyword",
        "store": "yes",
        "fields": {
          "pinyin": {
            "type": "text",
            "store": "no",
            "term_vector": "with_positions_offsets",
           "analyzer": "pinyin_analyzer",
           "boost": 10
          }
        }
      }
    }
  }
},
"aliases": {}
}

测试分词的时候，如果输入的汉字，搜索没有问题，如果用非汉字搜索时，就会出现问题，分词结果为：
{
-"tokens": [
-{
"token": "ce",
"start_offset": 0,
"end_offset": 4,
"type": "word",
"position": 0
},
-{
"token": "shi",
"start_offset": 0,
"end_offset": 4,
"type": "word",
"position": 1
},
-{
"token": "ceshi",
"start_offset": 0,
"end_offset": 5,
"type": "word",
"position": 2
},
-{
"token": "",
"start_offset": 0,
"end_offset": 0,
"type": "word",
"position": 3
}
]
}

由于最后一个的存在，就可以将非汉字的都查出来，这个与预期不一样，

不知道这个要怎么解决呢？

**Comment by medcl** [comment]
请问输入的查询是什么呢，麻烦提供一下

**Comment by liwei66** [comment]
测试分词为： {
  "text": "zhangsan",
  "field": "hcmPersName.pinyin"
}

**Comment by pengweigit** [comment]
你好，“21金维他”能分词成“21jwt”,"jinweita",  不能分成“21jinweita” (类似“维生素B1”也不能分成“weishengsub1”), 这个要怎么解决？

**Comment by medcl** [comment]
```
{
  "tokens": [
    {
      "token": "21",
      "start_offset": 1,
      "end_offset": 2,
      "type": "word",
      "position": 0
    },
    {
      "token": "jinweita",
      "start_offset": 0,
      "end_offset": 8,
      "type": "word",
      "position": 1
    },
    {
      "token": "21jwt",
      "start_offset": 0,
      "end_offset": 5,
      "type": "word",
      "position": 2
    }
  ]
}
```
```
{
  "tokens": [
    {
      "token": "b",
      "start_offset": 3,
      "end_offset": 4,
      "type": "word",
      "position": 0
    },
    {
      "token": "1",
      "start_offset": 4,
      "end_offset": 5,
      "type": "word",
      "position": 1
    },
    {
      "token": "weishengsu",
      "start_offset": 0,
      "end_offset": 10,
      "type": "word",
      "position": 2
    },
    {
      "token": "wssb1",
      "start_offset": 0,
      "end_offset": 5,
      "type": "word",
      "position": 3
    }
  ]
}
```
可以么？

**Comment by medcl** [comment]
```
PUT /medcl/
{
    "index" : {
        "analysis" : {
            "analyzer" : {
                "pinyin_analyzer" : {
                    "tokenizer" : "my_pinyin"
                    }
            },
            "tokenizer" : {
                "my_pinyin" : {
                    "type" : "pinyin",
                    "keep_separate_first_letter" : false,
                    "keep_full_pinyin" : false,
                    "keep_original" : false,
                    "limit_first_letter_length" : 16,
                    "lowercase" : true,
                    "keep_none_chinese":true,
                    "keep_joined_full_pinyin" : true,
                    "keep_first_letter":false,
                    "keep_none_chinese_in_first_letter":true,
                    "none_chinese_pinyin_tokenize":false
                }
            }
        }
    }
}
```
```
{
  "tokens": [
    {
      "token": "21",
      "start_offset": 0,
      "end_offset": 2,
      "type": "word",
      "position": 0
    },
    {
      "token": "jinweita",
      "start_offset": 0,
      "end_offset": 8,
      "type": "word",
      "position": 1
    }
  ]
}
```
```
{
  "tokens": [
    {
      "token": "b1",
      "start_offset": 2,
      "end_offset": 4,
      "type": "word",
      "position": 0
    },
    {
      "token": "weishengsu",
      "start_offset": 0,
      "end_offset": 10,
      "type": "word",
      "position": 1
    }
  ]
}
```

**Comment by medcl** [comment]
想要 b1和weishengsu不分开的，在上面的 commit 已支持

**Comment by pengweigit** [comment]
我的“刘德华2016”不能分成“liudehua2016”, 请问是为什么？
配置如下：
PUT /medcl
{
    "index": {
        "analysis": {
            "analyzer": {
                "pinyin_analyzer": {
                    "tokenizer": "my_pinyin"
                }
            },
            "tokenizer": {
                "my_pinyin": {
                    "type": "pinyin",
                    "keep_joined_full_pinyin ": true,
                    "none_chinese_pinyin_tokenize": false,
                    "keep_original": true,
                    "keep_none_chinese_in_joined_full_pinyin": true
                }
            }
        }
    }
}

GET medcl结果：

{
  "medcl": {
    "aliases": {},
    "mappings": {},
    "settings": {
      "index": {
        "number_of_shards": "5",
        "provided_name": "medcl",
        "creation_date": "1488506040966",
        "analysis": {
          "analyzer": {
            "pinyin_analyzer": {
              "tokenizer": "my_pinyin"
            }
          },
          "tokenizer": {
            "my_pinyin": {
              "none_chinese_pinyin_tokenize": "false",
              "type": "pinyin",
              "keep_none_chinese_in_joined_full_pinyin": "true",
              "keep_original": "true",
              "keep_joined_full_pinyin ": "true"
            }
          }
        },
        "number_of_replicas": "1",
        "uuid": "cQTLwKB5TF-g0urj56jmYw",
        "version": {
          "created": "5010199"
        }
      }
    }
  }
}


GET medcl/_analyze
{
  "text": ["刘德华2016"],
  "analyzer": "pinyin_analyzer"
}

结果如下：
{
  "tokens": [
    {
      "token": "liu",
      "start_offset": 0,
      "end_offset": 1,
      "type": "word",
      "position": 0
    },
    {
      "token": "de",
      "start_offset": 1,
      "end_offset": 2,
      "type": "word",
      "position": 1
    },
    {
      "token": "hua",
      "start_offset": 2,
      "end_offset": 3,
      "type": "word",
      "position": 2
    },
    {
      "token": "2016",
      "start_offset": 2,
      "end_offset": 6,
      "type": "word",
      "position": 3
    },
    {
      "token": "刘德华2016",
      "start_offset": 0,
      "end_offset": 7,
      "type": "word",
      "position": 4
    },
    {
      "token": "ldh2016",
      "start_offset": 0,
      "end_offset": 7,
      "type": "word",
      "position": 5
    }
  ]
}

***注： 我改了elasticsearch版本号为5.1.1如何打包插件的，不知道这个是否影响？***

**Comment by pengweigit** [comment]
我的elasticsearch版本为5.1.1

**Comment by medcl** [comment]
@pengweigit 最新的代码自己打包，或者下载5.2.2，用下面的配置
```
PUT /medcl/
{
  "index": {
    "analysis": {
      "analyzer": {
        "pinyin_analyzer": {
          "tokenizer": "my_pinyin"
        }
      },
      "tokenizer": {
        "my_pinyin": {
          "type": "pinyin",
          "keep_separate_first_letter": false,
          "keep_full_pinyin": false,
          "keep_original": false,
          "limit_first_letter_length": 16,
          "lowercase": true,
          "keep_first_letter": false,
          "keep_none_chinese_in_first_letter": false,
          "none_chinese_pinyin_tokenize": false,
          "keep_none_chinese": true,
          "keep_joined_full_pinyin": true,
          "keep_none_chinese_in_joined_full_pinyin": true
        }
      }
    }
  }
}
```

**Comment by pengweigit** [comment]
嗯，换成上面的配置可以分出来了，谢谢！
