### ISSUE TITLE
pinyin分词后的position问题

### ISSUE THREAD

**Issue by pengcong90** [medcl/elasticsearch-analysis-pinyin#83]
GET /rsc/_analyze
{
  "analyzer": "ik_pinyin_analyzer",
  "text": "彭聪"
}
使用推荐的ik加pinyin的方式ik_pinyin_analyzer
mapping
 "ik_pinyin_analyzer": {
                  "type": "custom",
                  "tokenizer": "ik_max_word",
                  "filter": [
                     "my_pinyin",
                     "word_delimiter"
                  ]
               }

分词后得到的结果
{
   "tokens": [
      {
         "token": "peng",
         "start_offset": 0,
         "end_offset": 1,
         "type": "CN_WORD",
         "position": 0
      },
      {
         "token": "p",
         "start_offset": 0,
         "end_offset": 1,
         "type": "CN_WORD",
         "position": 1
      },
      {
         "token": "cong",
         "start_offset": 1,
         "end_offset": 2,
         "type": "CN_WORD",
         "position": 2
      },
      {
         "token": "c",
         "start_offset": 1,
         "end_offset": 2,
         "type": "CN_WORD",
         "position": 3
      }
   ]
}
peng和从的position分别是0和2，这样导致了match_phrase会根据相对位置筛选的方式，查询不出结果了。

**Comment by pengcong90** [comment]
es5.1.1的版本，相应的pinyin分词也是5.1的

**Comment by medcl** [comment]
如果要用 phrase 查询，term 位置不能有重叠

**Comment by medcl** [comment]
README 已更新 phrase 的例子
