### ISSUE TITLE
keep_first_letter,keep_joined_full_pinyin,keep_full_pinyin 无法同时使用？

### ISSUE THREAD

**Issue by garycruise** [medcl/elasticsearch-analysis-pinyin#84]
环境:
  ES：5.1.1
  elasticsearch-analysis-pinyin:5.1.1
设置：
  "pinyin_completion_analyzer": {
                               "tokenizer": "whitespace",
                               "filter": "pinyin_first_letter_and_full_pinyin_filter"
                             }
  "filter": {
                           "pinyin_first_letter_and_full_pinyin_filter": {
                               "type": "pinyin",
                               "keep_none_chinese": true,
                               "keep_none_chinese_in_first_letter": true,
                               "keep_first_letter": true,
                               "keep_joined_full_pinyin": true,
                               "keep_full_pinyin": true,
                               "keep_original": false,
                               "limit_first_letter_length": 50,
                               "lowercase": true,
                               "trim_whitespace": true
                           }
                       }
用法（*pinyin_analyzer另行设置）：
 "title": {
            "type": "text",
            "fields": {
              "pinyin": {
                "type": "text",
                "term_vector": "with_positions_offsets",
                "analyzer": "pinyin_analyzer"
              }
            },
            "copy_to": [
              "title_completion"
            ],
            "analyzer": "ik_max_word"
          },
          "title_completion": {
            "type": "completion",
            "analyzer": "ik_max_word",
            "preserve_separators": true,
            "preserve_position_increments": true,
            "max_input_length": 50,
            "fields": {
              "pinyin": {
                "type": "completion",
                "analyzer": "pinyin_completion_analyzer",
                "search_analyzer": "simple",
                "preserve_separators": true,
                "preserve_position_increments": true,
                "max_input_length": 50
              }
            }
          }
问题：
 按照如下顺序
1. keep_first_letter
2. keep_joined_full_pinyin
3. keep_full_pinyin
设置为true后，只有最下层的可用。
例：
{
  "suggest-suggest": {
    "text": "input_word",
    "completion": {
      "field": "title_completion.pinyin",
      "size": 10
      }
    }
}
只激活keep_first_letter，则input_word为首字母时可以得到期待结果。
同时激活keep_first_letter和keep_joined_full_pinyin时input_word为连续拼音时有效，为首字母时得不到期待结果。
请问是用法设置有问题还是Bug？

**Comment by medcl** [comment]
你需要自带一个一个新的的类型，而不是直接修改参数：
`
DELETE medcl
PUT /medcl/
{
    "index" : {
        "analysis" : {
            "analyzer" : {
                "pinyin_analyzer" : {
                    "tokenizer" : "my_pinyin"
                    }
            },
            "tokenizer" : {
                "my_pinyin" : {
                    "type" : "pinyin",
                    "keep_first_letter":true,
                    "keep_separate_first_letter" : true,
                    "keep_full_pinyin" : true,
                    "keep_original" : false,
                    "limit_first_letter_length" : 16,
                    "lowercase" : true,
                    "keep_joined_full_pinyin":true
                }
            }
        }
    }
}

POST /medcl/folks/_mapping
{
    "folks": {
        "properties": {
            "name": {
                "type": "keyword",
                "fields": {
                    "pinyin": {
                        "type": "text",
                        "store": "no",
                        "term_vector": "with_positions_offsets",
                        "analyzer": "pinyin_analyzer",
                        "boost": 10
                    }
                }
            }
        }
    }
}
GET /medcl/_analyze
{
  "text": ["刘德华12"],
  "analyzer": "pinyin_analyzer"
}
`

`
{
  "tokens": [
    {
      "token": "l",
      "start_offset": 0,
      "end_offset": 1,
      "type": "word",
      "position": 0
    },
    {
      "token": "liu",
      "start_offset": 0,
      "end_offset": 1,
      "type": "word",
      "position": 1
    },
    {
      "token": "d",
      "start_offset": 1,
      "end_offset": 2,
      "type": "word",
      "position": 2
    },
    {
      "token": "de",
      "start_offset": 1,
      "end_offset": 2,
      "type": "word",
      "position": 3
    },
    {
      "token": "h",
      "start_offset": 2,
      "end_offset": 3,
      "type": "word",
      "position": 4
    },
    {
      "token": "hua",
      "start_offset": 2,
      "end_offset": 3,
      "type": "word",
      "position": 5
    },
    {
      "token": "12",
      "start_offset": 3,
      "end_offset": 4,
      "type": "word",
      "position": 6
    },
    {
      "token": "liudehua",
      "start_offset": 0,
      "end_offset": 8,
      "type": "word",
      "position": 7
    },
    {
      "token": "ldh12",
      "start_offset": 0,
      "end_offset": 5,
      "type": "word",
      "position": 8
    }
  ]
}
`

**Comment by garycruise** [comment]
感谢回答。
原意是想通过copy_to和multi_field实现输入数据时只需要一个属性，却能同时实现汉子/拼音搜索和汉子/拼音自动补全。
已经摸索出解决方法了。
谢谢。

**Comment by shaoslu** [comment]
@garycruise 你好，你这个是怎么解决的呢？
