### ISSUE TITLE
为什么我建索引的时候必须配置filter“nGram”才能在搜索的时候输入拼音得到数据？

### ISSUE THREAD

**Issue by ganxiaomao** [medcl/elasticsearch-analysis-pinyin#9]
我碰到的问题就是如标题所述。我的想法是只按照完整的拼音来建索引，所以按照文档里的第一种方式来配置pinyin analyzer：
curl -XPUT http://localhost:9200/medcl/ -d'
{
    "index" : {
        "analysis" : {
            "analyzer" : {
                "pinyin_analyzer" : {
                    "tokenizer" : "my_pinyin",
                    "filter" : ["standard"]
                }
            },
            "tokenizer" : {
                "my_pinyin" : {
                    "type" : "pinyin",
                    "first_letter" : "none",
                    "padding_char" : " "
                }
            }
        }
    }
}'
mapping的配置如下：
curl -XPOST localhost:9200/searchshowindex_v3/searchshowtype/_mapping -d'
{                
"searchshowtype":{
"_all":{"analyzer":"pinyin_analyzer","term_vector":"no","store":false}
}}'
但是对数据索引之后，在地址栏中随便输入无论什么样的拼音，即便是一个字母的也得不到任何结果，必须在filter里面配置nGram才有结果，但这又不是我要的，配了nGram无论输入什么拼音基本上所有的数据都能被搜索到，这个体验不好。
所以想问一下medcl为什么会发生这种问题，是我哪里理解错了，没有配好？如果方便的话麻烦能帮我解决这一疑惑。

**Comment by liukaitj** [comment]
这个问题有解决么？我现在遇到了同样的问题。。

**Comment by medcl** [comment]
拼音插件只做一件事情,就是把"中文"=>"zhongwen",所以默认是完整的pinyin,是一个整体,如果你需要模糊匹配,那就进一步分词处理,配置一个filter,ngramFilter可以对"zhongwen"进一步切分,比如成:"zh"\"ho"\"on"等,这样你就可以模糊搜索了

**Comment by liukaitj** [comment]
但是ngramFilter又会将所有包含的"zh"、"on"的文档匹配出来，这显然不是通常想要的结果。有没有一个介于两者之间，比如切分成"zhong"、"wen"的filter？

**Comment by liukaitj** [comment]
我又查了下，貌似是my_pinyin这个tokenizer有点问题，比如“全国首发”这四个字，在ES内部被tokenize成了"quan guo shou fa"一个整体，而不是"quan"、"guo"、"shou"、"fa"这四个token，我看my_pinyin下的padding_char参数设置的是一个空格啊，怎么tokenize不起作用呢？好奇怪。。

**Comment by medcl** [comment]
你用whitespace或者standard filter，拼音的padding char设置空格，按空格切

send via my Phone.

**Comment by medcl** [comment]
padding只是在不同拼音间加隔断，未切哦

send via my Phone.

**Comment by ganxiaomao** [comment]
非常感谢你的回复，我来试试

在 2015-08-04 19:53:11，"Medcl" <notifications@github.com> 写道：
你用whitespace或者standard filter，拼音的padding char设置空格，按空格切

send via my Phone.

**Comment by liukaitj** [comment]
不用ngram了，匹配得太不准确了。扩展了一个基于IK分词的拼音插件，放在这了：https://github.com/liukaitj/elasticsearch-analysis-ik-pinyin  ，可以根据IK分词出来的短语进行拼音匹配，避免了过度匹配问题。

**Comment by medcl** [comment]
其实你使用一个ik的tokenizer，再加一个拼音的filter就行了

send via my Phone.
