### ISSUE TITLE
我想用这个拼音插件做完成建议（completion suggester），请问应该如何配置呢？

### ISSUE THREAD

**Issue by shaoslu** [medcl/elasticsearch-analysis-pinyin#91]
一直配置不成功，需要支持拼音首字母，全拼，和中文匹配，下面是我自己配置的，但不支持首字母匹配
```
{
    "index" : {
        "analysis" : {
            "analyzer" : {
                "user_name_analyzer" : {
                    "tokenizer" : "ik_max_word",
                    "filter" : "full_pinyin_filter"
                }
            },
            "filter" : {
                "full_pinyin_filter" : {
                    "type" : "pinyin",
                    "keep_first_letter" : false,
                    "keep_full_pinyin" : true,
                    "keep_none_chinese" : true,
                    "keep_separate_first_letter" : true,
                    "keep_original" : false,
                    "limit_first_letter_length" : 16,
                    "lowercase" : true,
                    "trim_whitespace" : true,
                    "keep_none_chinese_in_first_letter" : true
                }
            }
        }
    }
}
```

**Comment by anuo12003** [comment]
我也有同样的问题，各种试验都不成功，请问最后做出来了吗？

**Comment by shaoslu** [comment]
@anuo12003，做出来了，我其实是分成三个字段，一个是中文分词，一个是全拼，还有一个是首字母这样去查的，但是没用到completion suggester

**Comment by anuo12003** [comment]
@shaoslu 能把具体的分词器设置，和首字母查询的代码发给我参考一下吗？实在没有思路了！多谢

**Comment by shaoslu** [comment]
@anuo12003 

下面是分析器的设置和字段的映射，查询语句是用了 match_phrase_prefix
```
{
    "settings" : {
        "analysis" : {
            "analyzer" : {
                "first_py_letter_analyzer" : {
                    "tokenizer" : "first_py_letter"
                },
                "full_pinyin_letter_analyzer" : {
                    "tokenizer" : "full_pinyin_letter"
                }
            },
            "tokenizer" : {
                "first_py_letter" : {
                    "type" : "pinyin",
                    "keep_first_letter" : true,
                    "keep_full_pinyin" : false,
                    "keep_none_chinese" : true,
                    "keep_original" : false,
                    "limit_first_letter_length" : 16,
                    "lowercase" : true,
                    "trim_whitespace" : true,
                    "keep_none_chinese_in_first_letter" : true
                },
                "full_pinyin_letter" : {
                    "type": "pinyin",
                    "keep_separate_first_letter": false,
                    "keep_full_pinyin": true,
                    "keep_original": false,
                    "limit_first_letter_length": 16,
                    "lowercase": true,
                    "keep_first_letter": false,
                    "keep_none_chinese_in_first_letter": false,
                    "none_chinese_pinyin_tokenize": false,
                    "keep_none_chinese": true,
                    "keep_joined_full_pinyin": true,
                    "keep_none_chinese_in_joined_full_pinyin": true
                }
            }
        },
        "number_of_shards": 5,
        "number_of_replicas": 1
    },
    "mappings":{
        "suggestion":{
            "properties": {
                "keyword": {
                    "type": "keyword",
                    "fields": {
                        "keyword_ik": {
                            "type": "text",
                            "analyzer": "ik_max_word"
                        },
                        "keyword_pinyin": {
                            "type": "text",
                            "analyzer": "full_pinyin_letter_analyzer"
                        },
                        "keyword_first_py": {
                            "type": "text",
                            "analyzer": "first_py_letter_analyzer"
                        }
                    }
                },              
                "count": {
                    "type": "long",
                    "index": "not_analyzed"
                },
                "weight": {
                    "type": "integer",
                    "index": "not_analyzed"
                }
            }
        }        
    }
}
```

**Comment by shaoslu** [comment]
@anuo12003  
分析器和映射：
```
{
    "settings" : {
        "analysis" : {
            "analyzer" : {
                "first_py_letter_analyzer" : {
                    "tokenizer" : "first_py_letter"
                },
                "full_pinyin_letter_analyzer" : {
                    "tokenizer" : "full_pinyin_letter"
                }
            },
            "tokenizer" : {
                "first_py_letter" : {
                    "type" : "pinyin",
                    "keep_first_letter" : true,
                    "keep_full_pinyin" : false,
                    "keep_original" : false,
                    "limit_first_letter_length" : 16,
                    "lowercase" : true,
                    "trim_whitespace" : true,
                    "keep_none_chinese_in_first_letter": false,
                    "none_chinese_pinyin_tokenize": false,
                    "keep_none_chinese": true,
                    "keep_none_chinese_in_joined_full_pinyin": true
                },
                "full_pinyin_letter" : {
                    "type": "pinyin",
                    "keep_separate_first_letter": false,
                    "keep_full_pinyin": false,
                    "keep_original": false,
                    "limit_first_letter_length": 16,
                    "lowercase": true,
                    "keep_first_letter": false,
                    "keep_none_chinese_in_first_letter": false,
                    "none_chinese_pinyin_tokenize": false,
                    "keep_none_chinese": true,
                    "keep_joined_full_pinyin": true,
                    "keep_none_chinese_in_joined_full_pinyin": true
                }
            }
        },
        "number_of_shards": 5,
        "number_of_replicas": 1
    },
    "mappings":{
        "suggestion":{
            "properties": {
                "keyword": {
                    "type": "keyword",
                    "fields": {
                        "keyword_ik": {
                            "type": "text",
                            "analyzer": "ik_max_word"
                        },
                        "keyword_pinyin": {
                            "type": "text",
                            "analyzer": "full_pinyin_letter_analyzer"
                        },
                        "keyword_first_py": {
                            "type": "text",
                            "analyzer": "first_py_letter_analyzer"
                        }
                    }
                },              
                "count": {
                    "type": "long",
                    "index": "not_analyzed"
                },
                "weight": {
                    "type": "integer",
                    "index": "not_analyzed"
                }
            }
        }        
    }
}
```
查询代码是：

```
{
    "sort": [
        {
            "weight": "desc"
        },
        {
            "count": "desc"
        },
        {
            "_score": "desc"
        }
    ],
    "query": {
        "bool": {
            "must": {
                "bool": {
                    "should": [
                        {
                            "match_phrase_prefix": {
                                "keyword.keyword_pinyin": {
                                    "query": "albb",
                                    "boost": 2
                                }
                            }
                        },
                        {
                            "match_phrase_prefix": {
                                "keyword.keyword_first_py": {
                                    "query": "albb",
                                    "boost": 1
                                }
                            }
                        }
                    ]
                }
            }
        }
    }
}
```

**Comment by xiaoxiaojuan** [comment]
@shaoslu 我用你的这个建了索引，可是keyword_ik, keyword_pinyin不起作用。。。。

curl -XPUT http://localhost:9200/nausicaa -d'
{
    "settings" : {
        "analysis" : {
            "analyzer" : {
                "first_py_letter_analyzer" : {
                    "tokenizer" : "first_py_letter"
                },
                "full_pinyin_letter_analyzer" : {
                    "tokenizer" : "full_pinyin_letter"
                }
            },
            "tokenizer" : {
                "first_py_letter" : {
                    "type" : "pinyin",
                    "keep_first_letter" : true,
                    "keep_full_pinyin" : false,
                    "keep_original" : false,
                    "limit_first_letter_length" : 16,
                    "lowercase" : true,
                    "trim_whitespace" : true,
                    "keep_none_chinese_in_first_letter": false,
                    "none_chinese_pinyin_tokenize": false,
                    "keep_none_chinese": true,
                    "keep_none_chinese_in_joined_full_pinyin": true
                },
                "full_pinyin_letter" : {
                    "type": "pinyin",
                    "keep_separate_first_letter": false,
                    "keep_full_pinyin": true,
                    "keep_original": false,
                    "limit_first_letter_length": 16,
                    "lowercase": true,
                    "keep_first_letter": false,
                    "keep_none_chinese_in_first_letter": false,
                    "none_chinese_pinyin_tokenize": false,
                    "keep_none_chinese": true,
                    "keep_joined_full_pinyin": true,
                    "keep_none_chinese_in_joined_full_pinyin": true
                }
            }
        },
        "number_of_shards": 1,
        "number_of_replicas": 0
    },
    "mappings":{
        "suggestion":{
            "properties": {
                "name": {
                    "type": "text",
                    "index": "analyzed",
                    "fields": {
                        "name_ik": {
                            "type": "text",
                            "analyzer": "ik_max_word"
                        },
                        "name_pinyin": {
                            "type": "text",
                            "analyzer": "full_pinyin_letter_analyzer"
                        },
                        "name_first_py": {
                            "type": "text",
                            "analyzer": "first_py_letter_analyzer"
                        }
                    }
                }

            }
        }
    }
}'


查询语句如下，能帮我看下么
curl -XGET   http://localhost:9200/nausicaa/productmovie/_search -d'
{
  "query": {
    "multi_match": {
      "type": "best_fields",
      "query":  "名侦探",
      "fields": "name.name_pinyin"
    }
  }
}'

**Comment by xiaoxiaojuan** [comment]
@shaoslu 我用你的配置但是fields 不起作用呢，能帮我看下么

curl -XPUT http://localhost:9200/nausicaa -d'
{
    "settings" : {
        "analysis" : {
            "analyzer" : {
                "first_py_letter_analyzer" : {
                    "tokenizer" : "first_py_letter"
                },
                "full_pinyin_letter_analyzer" : {
                    "tokenizer" : "full_pinyin_letter"
                }
            },
            "tokenizer" : {
                "first_py_letter" : {
                    "type" : "pinyin",
                    "keep_first_letter" : true,
                    "keep_full_pinyin" : false,
                    "keep_original" : false,
                    "limit_first_letter_length" : 16,
                    "lowercase" : true,
                    "trim_whitespace" : true,
                    "keep_none_chinese_in_first_letter": false,
                    "none_chinese_pinyin_tokenize": false,
                    "keep_none_chinese": true,
                    "keep_none_chinese_in_joined_full_pinyin": true
                },
                "full_pinyin_letter" : {
                    "type": "pinyin",
                    "keep_separate_first_letter": false,
                    "keep_full_pinyin": true,
                    "keep_original": false,
                    "limit_first_letter_length": 16,
                    "lowercase": true,
                    "keep_first_letter": false,
                    "keep_none_chinese_in_first_letter": false,
                    "none_chinese_pinyin_tokenize": false,
                    "keep_none_chinese": true,
                    "keep_joined_full_pinyin": true,
                    "keep_none_chinese_in_joined_full_pinyin": true
                }
            }
        },
        "number_of_shards": 1,
        "number_of_replicas": 0
    },
    "mappings":{
        "suggestion":{
            "properties": {
                "name": {
                    "type": "text",
                    "index": "analyzed",
                    "fields": {
                        "name_ik": {
                            "type": "text",
                            "analyzer": "ik_max_word"
                        },
                        "name_pinyin": {
                            "type": "text",
                            "analyzer": "full_pinyin_letter_analyzer"
                        },
                        "name_first_py": {
                            "type": "text",
                            "analyzer": "first_py_letter_analyzer"
                        }
                    }
                }

            }
        }
    }
}'

查询语句如下：
curl -XGET   http://localhost:9200/nausicaa/productmovie/_search -d'
{
  "query": {
    "multi_match": {
      "type": "best_fields",
      "query":  "mingzhentan",
      "fields": "name", "name.name_pinyin", "name.name_first_py" ]
    }
  }
}'

**Comment by xiaoxiaojuan** [comment]
@shaoslu 你好，我套用你的配置，但是fields字段不起作用呢，能帮忙看下么
curl -XPUT http://localhost:9200/nausicaa/ -d'
{
    "settings" : {
        "analysis" : {
            "analyzer" : {
                "first_py_letter_analyzer" : {
                    "tokenizer" : "first_py_letter"
                },
                "full_pinyin_letter_analyzer" : {
                    "tokenizer" : "full_pinyin_letter"
                }
            },
            "tokenizer" : {
                "first_py_letter" : {
                    "type" : "pinyin",
                    "keep_first_letter" : true,
                    "keep_full_pinyin" : false,
                    "keep_original" : false,
                    "limit_first_letter_length" : 16,
                    "lowercase" : true,
                    "trim_whitespace" : true,
                    "keep_none_chinese_in_first_letter": false,
                    "none_chinese_pinyin_tokenize": false,
                    "keep_none_chinese": true,
                    "keep_none_chinese_in_joined_full_pinyin": true
                },
                "full_pinyin_letter" : {
                    "type": "pinyin",
                    "keep_separate_first_letter": false,
                    "keep_full_pinyin": true,
                    "keep_original": false,
                    "limit_first_letter_length": 16,
                    "lowercase": true,
                    "keep_first_letter": false,
                    "keep_none_chinese_in_first_letter": false,
                    "none_chinese_pinyin_tokenize": false,
                    "keep_none_chinese": true,
                    "keep_joined_full_pinyin": true,
                    "keep_none_chinese_in_joined_full_pinyin": true
                }
            }
        },
        "number_of_shards": 1,
        "number_of_replicas": 0
    },
    "mappings":{
        "suggestion":{
            "properties": {
                "name": {
                    "type": "text",
                    "index": "analyzed",
                    "fields": {
                        "name_ik": {
                            "type": "text",
                            "analyzer": "ik_max_word"
                        },
                        "name_pinyin": {
                            "type": "text",
                            "analyzer": "full_pinyin_letter_analyzer"
                        },
                        "name_first_py": {
                            "type": "text",
                            "analyzer": "first_py_letter_analyzer"
                        }
                    }
                }

            }
        }
    }
}'

查询语句如下
curl -XGET   http://localhost:9200/nausicaa/productmovie/_search -d'
{
  "query": {
    "multi_match": {
      "type": "best_fields",
      "query":  "mingzhentan",
      "fields": "name.name_pinyin"
    }
  }
}'

**Comment by shaoslu** [comment]
@xiaoxiaojuan 
你的需求是什么，我看你分析器的配置都改得和我的不一样，还有你映射的type是suggetsion，但查询用的却是productmovie

**Comment by xiaoxiaojuan** [comment]
@shaoslu 谢谢你的回复，
我是要搜索表productmovie的几个字段，其中有一个字段是中文，拼音，拼音缩写，还有的字段是需要中文英文的分词。
我用的elasticsearch-rtf插件都装好了，拼音分词单独测试起作用，但是套用你这个不起作用，所以我觉得哪里设置的不对。suggestions那个改成productmovie了也不行呢。

curl -XPUT http://localhost:9200/nausicaa/ -d'
{
    "settings" : {
        "analysis" : {
            "analyzer" : {
                "first_py_letter_analyzer" : {
                    "tokenizer" : "first_py_letter"
                },
                "full_pinyin_letter_analyzer" : {
                    "tokenizer" : "full_pinyin_letter"
                }
            },
            "tokenizer" : {
                "first_py_letter" : {
                    "type" : "pinyin",
                    "keep_first_letter" : true,
                    "keep_full_pinyin" : false,
                    "keep_original" : false,
                    "limit_first_letter_length" : 16,
                    "lowercase" : true,
                    "trim_whitespace" : true,
                    "keep_none_chinese_in_first_letter": false,
                    "none_chinese_pinyin_tokenize": false,
                    "keep_none_chinese": true,
                    "keep_none_chinese_in_joined_full_pinyin": true
                },
                "full_pinyin_letter" : {
                    "type": "pinyin",
                    "keep_separate_first_letter": false,
                    "keep_full_pinyin": true,
                    "keep_original": false,
                    "limit_first_letter_length": 16,
                    "lowercase": true,
                    "keep_first_letter": false,
                    "keep_none_chinese_in_first_letter": false,
                    "none_chinese_pinyin_tokenize": false,
                    "keep_none_chinese": true,
                    "keep_joined_full_pinyin": true,
                    "keep_none_chinese_in_joined_full_pinyin": true
                }
            }
        },
        "number_of_shards": 1,
        "number_of_replicas": 0
    },
    "mappings":{
        "productmovie":{
            "properties": {
                "name": {
                    "type": "keyword",
                    "index": "analyzed",
                    "fields": {
                        "name_ik": {
                            "type": "text",
                            "analyzer": "ik_max_word"
                        },
                        "name_pinyin": {
                            "type": "text",
                            "analyzer": "full_pinyin_letter_analyzer"
                        },
                        "name_first_py": {
                            "type": "text",
                            "analyzer": "first_py_letter_analyzer"
                        }
                    }
                }

            }
        }
    }
}'

查询语句
bogon:Search ruby$ curl -XGET   http://localhost:9200/nausicaa/productmovie/_search -d'
> {
>   "query": {
>     "multi_match": {
>       "type": "best_fields",
>       "query":  "mingzhentan",
>       "fields": "name.name_pinyin"
>     }
>   }
> }'

查询结果
{"took":4,"timed_out":false,"_shards":{"total":1,"successful":1,"failed":0},"hits":{"total":0,"max_score":null,"hits":[]}}bogon:Search ruby$

**Comment by shaoslu** [comment]
@xiaoxiaojuan 
哦，因为我的需求是搜索建议，所以那个分析器只适合前缀查询的，你要用match查询的话分析器得改改，你试试下面的：
```
{
    "settings": {
        "analysis": {
            "analyzer": {
                "first_py_letter_analyzer": {
                    "tokenizer": "first_py_letter"
                },
                "full_pinyin_letter_analyzer": {
                    "tokenizer": "full_pinyin_letter"
                }
            },
            "tokenizer": {
                "first_py_letter": {
                    "type" : "pinyin",
                    "keep_first_letter" : true,
                    "keep_full_pinyin" : false,
                    "keep_none_chinese" : true,
                    "keep_original" : false,
                    "limit_first_letter_length" : 16,
                    "lowercase" : true,
                    "trim_whitespace" : true,
                    "keep_none_chinese_in_first_letter" : true
                },
                "full_pinyin_letter": {
                    "type" : "pinyin",
                    "keep_first_letter" : false,
                    "keep_full_pinyin" : true,
                    "keep_none_chinese" : true,
                    "keep_separate_first_letter" : true,
                    "keep_original" : false,
                    "limit_first_letter_length" : 16,
                    "lowercase" : true,
                    "trim_whitespace" : true,
                    "keep_none_chinese_in_first_letter" : true
                }
            }
        },
        "number_of_shards": 1,
        "number_of_replicas": 0
    },
    "mappings": {
        "productmovie": {
            "properties": {
                "name": {
                    "type": "keyword",
                    "index": "analyzed",
                    "fields": {
                        "name_ik": {
                            "type": "text",
                            "analyzer": "ik_max_word"
                        },
                        "name_pinyin": {
                            "type": "text",
                            "analyzer": "full_pinyin_letter_analyzer"
                        },
                        "name_first_py": {
                            "type": "text",
                            "analyzer": "first_py_letter_analyzer"
                        }
                    }
                }
            }
        }
    }
}
```

**Comment by xiaoxiaojuan** [comment]
@shaoslu 😄非常感谢，现在拼音生效了，但是奇怪的是用首字母去查询的时候出来的结果不是预期的，比如
curl -XGET   http://localhost:9200/nausicaa/productmovie/_search -d'
{
  "query": {
    "multi_match": {
      "type": "best_fields",
      "query":  "mztkn",
      "fields": "name.name_first_py"
    }
  }
}'
希望是出来：名侦探柯南

但是出来的是
深夜的FM

查了下first_py_letter 的参数，觉得没啥问题，不知道问题出那里了。

**Comment by shaoslu** [comment]
@xiaoxiaojuan 
上面的配置我重新改了下，你再试试看

**Comment by xiaoxiaojuan** [comment]
@shaoslu 😄太厉害了，能搜出来了，这些参数你是怎么研究出来的？

**Comment by shaoslu** [comment]
@xiaoxiaojuan 哈，这个自己多调试就好了

**Comment by xiaoxiaojuan** [comment]
@shaoslu 非常感谢shaoslu，太腻害了👍

**Comment by anuo12003** [comment]
@shaoslu 多谢你的答复，可惜的是我用的是es2.4版本，有些东西2.4里面还没有，比如keyword这个type，还有match_phrase_prefix这个查询类型。另外我想问一下，这种方式能做到和百度一样吗？比如不只是拼音首字母，或者全拼，能不能首字母和全拼和汉字穿插着查？

**Comment by anuo12003** [comment]
@shaoslu 我按你的这种方式，汉字和拼音首字母能够实现了，但是全拼不行，我在索引数据的时候，会报错说first_letter和full_pinyin不能同时设为false，将keep_full_pinyin设为true就能正常索引数据，但是全拼自动补全不行，不知道是不是这里的问题

**Comment by shaoslu** [comment]
@anuo12003 你的es是什么版本，我用的是5.2.2，没有你说的问题哈

**Comment by anuo12003** [comment]
@shaoslu 我的2.44版本，创建索引的时候没问题，导入数据的时候就报我说的那个first_letter和full_pinyin不能同时设为false的问题

**Comment by morningsky** [comment]
@shaoslu 您好，请问对于中英文混合搜索该怎么写配置文件呢？ 比如阿里bb
