### ISSUE TITLE
Query on Documentation

### ISSUE THREAD

**Issue by ashishmundrajll** [medcl/elasticsearch-analysis-pinyin#94]
I am new to elasticsearch but need to add this plugin to ElasticSearch.

Q1. Can I clone latest from master and will it work for ElasticSearch 2.3.1 version or should I get latest from 2.x branch?

Q2. When I did maven clean build, it generated elasticsearch-analysis-pinyin-5.2.2.jar file in target, but I do not see pinyin4j-2.5.0.jar in lib as pointed in this article - https://my.oschina.net/xiaohui249/blog/214505 (I do not know chinese so do not understand the full blog).

Can we please update Readme.md file to reflect these please?

Thanks and regards,
Ashish

**Comment by medcl** [comment]
Hey, to your questions?
1.it works on 2.x branch
2.it doesn't matter, this blog is kindly out of date, this project changed from pinyin4j to nlp-tools under the hood.

**Comment by ashishmundrajll** [comment]
Thanks much for prompt response. So for ElasticSearch 2.3.1, I should take latest of 2.x branch is what I understand.

I did that and maven build generated the file by name which has 5.2.2 in its filename - elasticsearch-analysis-pinyin-5.2.2.jar in target folder. I hope this will work for ElasticSearch2.3.1. It would have been great if the filename generated was elasticsearch-analysis-pinyin-2.x.jar

I also see a file named nlp-lang-1.7.jar in lib folder. 

What all files should I copy to plugin\pinyin folder on my Elastic Search server?

Thanks,
Ashish

**Comment by medcl** [comment]
can you check out the release folder?

**Comment by medcl** [comment]
also check out this if you prefer:
https://github.com/medcl/elasticsearch-analysis-pinyin/releases/tag/v1.8.4

**Comment by ashishmundrajll** [comment]
Sure, I will try extracting zip file contents to ES_HOME plugins\pinyin folder and will restart Elastic Search. Will report back once that works. Thanks for quick responses.

**Comment by ashishmundrajll** [comment]
I unzipped 1.8.4 and copied to plugins\pinyin folder. On stop and start Elastic Search (we have it on a Windows 64 bit machine), the Elastic Search windows service fails and error message is Incorrect Function.

java.lang.IllegalArgumentException: Plugin [analysis-pinyin] is incompatible with Elasticsearch [2.3.1]. Was designed for version [2.4.3]
	at org.elasticsearch.plugins.PluginInfo.readFromProperties(PluginInfo.java:118)
	at org.elasticsearch.plugins.PluginsService.getPluginBundles(PluginsService.java:378)
	at org.elasticsearch.plugins.PluginsService.<init>(PluginsService.java:128)
	at org.elasticsearch.node.Node.<init>(Node.java:158)
	at org.elasticsearch.node.Node.<init>(Node.java:140)
	at org.elasticsearch.node.NodeBuilder.build(NodeBuilder.java:143)
	at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:178)
	at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:270)
	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:35)

**Comment by medcl** [comment]
please try to use the correct version。
