### ISSUE TITLE
关于前缀匹配的问题

### ISSUE THREAD

**Issue by raycs078** [medcl/elasticsearch-analysis-pinyin#95]
最近想基于elasticsearch 做中文suggest。 不知道目前支持前缀搜索么？比如 刘德 ->刘德华, 建->建设。

**Comment by hufuman** [comment]
为什么不先尝试一下

**Comment by owenliang** [comment]
显然不支持。

**Comment by medcl** [comment]
当然是支持的，和本插件无关，不管是中文还是英文，分词的结果是完整的串（使用keyword类型），使用prefix查询。

**Comment by medcl** [comment]
拼音插件也支持分词成ldh或者liudehua，使用prefix查询就可以了
