### ISSUE TITLE
pinyin tokenizer 和 token-filter都做了什么？

### ISSUE THREAD

**Issue by anuo12003** [medcl/elasticsearch-analysis-pinyin#96]
如题，这两个东西在插件中都起到了什么作用，尤其是这个filter，比如我用ik做tokenizer，用pinyin做filter，pinyin会对ik分词结果作何处理？如果ik分词器分出来的是一个一个的整词，通过pinyin filter过滤后，还是完整的词的拼音码？

**Comment by medcl** [comment]
1.filter 会对 tokenizer 的结果转 pinyin，具体转成什么拼音，看你配置如何定义
