### ISSUE TITLE
请问1.8.1版本中的pinyin config error, can't disable first_letter and full_pinyin at the same time有没有解决办法

### ISSUE THREAD

**Issue by anuo12003** [medcl/elasticsearch-analysis-pinyin#97]
如题，我向做全拼的前缀匹配，创建索引的时候报这个错
pinyin config error, can't disable first_letter and full_pinyin at the same time，
请问，有没有什么好的办法解决一下呢？或者有没有别的全拼前缀匹配的配置的案例？

**Comment by medcl** [comment]
请问你需要的格式是什么呢？
是这个么？
https://github.com/medcl/elasticsearch-analysis-pinyin/blob/master/src/test/java/org/elasticsearch/index/analysis/PinyinAnalysisTests.java#L721

**Comment by anuo12003** [comment]
是的，我想要的就是这个，但是我看1.8.1版本的源码中的PinyinConfig中没有定义这个属性。我们因为系统环境所限，jdk只能到1.7，es5以上的版本用不了，所以拼音插件也就能到这个版本了。

**Comment by anuo12003** [comment]
是的，我就是想用这个属性，1.8.1没有这个属性，1.8.4中有，版本下的不对，不还要意思

**Comment by medcl** [comment]
那换新的版本吧
