### ISSUE TITLE
elasticsearch-analysis-pinyin 不能很好的获得首字母查询的问题

### ISSUE THREAD

**Issue by ApprenticeMythology** [medcl/elasticsearch-analysis-pinyin#98]
hi
我正在学习使用elasticsearch 和分词，版本是5.1.1 版本，IK和pinyin 分词分别是从github上下载的已经release 的5.1.1 版本
创建了如下的样例索引和mapping 配置：
curl -XPUT "http://localhost:9200/metadata/" -d'
{
    "index": {
        "analysis": {
            "analyzer": {
                "ik_pinyin_analyzer": {
                    "type": "custom",
                    "tokenizer": "ik_smart",
                    "filter": ["my_pinyin", "word_delimiter"]
                }
            },
            "filter": {
                "my_pinyin": {
                    "type": "pinyin",
                    "first_letter": "prefix",
                    "padding_char": " "
                }
            }
        }
    }
}'

curl -XPOST http://localhost:9200/metadata/movies/_mapping -d'
{
    "movies": {
        "properties": {
            "workName": {
                "type": "keyword",
                "fields": {
                    "pinyin": {
                        "type": "text",
                        "store": "no",
                        "term_vector": "with_positions_offsets",
                        "analyzer": "ik_pinyin_analyzer",
                        "boost": 10
                    }
                }
            }
        }
    }
}'
然后在执行搜索时，发现整体上首字母查询到的结果都不是想要的，但是全拼字母查询的结果很好。
比如其中有这样的一个文档：
{"index": {"_id": "4"}}
{"workName": "屠龙少年历险记","type": "冒险"}
执行查询，可以获得期望的结果：
http://localhost:9200/metadata/movies/_search?pretty&q=workName.pinyin:tulong

执行如下的首字母查询，但是查不到上面的那条数据
http://localhost:9200/metadata/movies/_search?pretty&q=workName.pinyin:tlsnlxj

分词的情况：
http://localhost:9200/metadata/_analyze?analyzer=pinyin&text=屠龙少年历险记
{"tokens":[{"token":"tu","start_offset":0,"end_offset":1,"type":"word","position":0},{"token":"long","start_offset":1,"end_offset":2,"type":"word","position":1},{"token":"shao","start_offset":2,"end_offset":3,"type":"word","position":2},{"token":"nian","start_offset":3,"end_offset":4,"type":"word","position":3},{"token":"li","start_offset":4,"end_offset":5,"type":"word","position":4},{"token":"xian","start_offset":5,"end_offset":6,"type":"word","position":5},{"token":"ji","start_offset":6,"end_offset":7,"type":"word","position":6},{"token":"tlsnlxj","start_offset":0,"end_offset":7,"type":"word","position":7}]}

http://localhost:9200/metadata/_analyze?analyzer=pinyin&text=tlsnlxj
{"tokens":[{"token":"t","start_offset":0,"end_offset":6,"type":"word","position":0},{"token":"l","start_offset":0,"end_offset":6,"type":"word","position":1},{"token":"s","start_offset":0,"end_offset":6,"type":"word","position":2},{"token":"nlxj","start_offset":0,"end_offset":6,"type":"word","position":3},{"token":"tlsnlxj","start_offset":0,"end_offset":7,"type":"word","position":4}]}

期待nubility的人给看看呢~~~

**Comment by medcl** [comment]
```
"first_letter": "prefix",
"padding_char": " "
```
上面的参数已经不支持了，如果要支持单字，可以加上参数：keep_separate_first_letter，建议中文和 pinyin 分开建字段
